-- +goose Up
-- +goose StatementBegin
INSERT INTO categories (parent_id, organization_id, name, slug, sort_order) VALUES
(NULL, NULL, 'Structural & Framing', 'structural-framing', 10)
, (NULL, NULL, 'Flooring', 'flooring', 20)
, (NULL, NULL, 'Ceiling', 'ceiling', 30)
, (NULL, NULL, 'Walls & Plastering', 'walls-plastering', 40)
, (NULL, NULL, 'Doors & Windows', 'doors-windows', 50)
, (NULL, NULL, 'Electrical', 'electrical', 60)
, (NULL, NULL, 'Plumbing', 'plumbing', 70)
, (NULL, NULL, 'Painting & Finishing', 'painting-finishing', 80)
, (NULL, NULL, 'Roofing', 'roofing', 90)
, (NULL, NULL, 'Hardware & Fasteners', 'hardware-fasteners', 100)
, (NULL, NULL, 'Lighting', 'lighting', 110)
, (NULL, NULL, 'Kitchen', 'kitchen', 120)
, (NULL, NULL, 'Bathroom', 'bathroom', 130)
, (NULL, NULL, 'Insulation', 'insulation', 140)
, (NULL, NULL, 'Tools & Equipment', 'tools-equipment', 150);

INSERT INTO categories (parent_id, organization_id, name, slug, sort_order)
SELECT
    p.id
    , c.organization_id
    , c.name
    , c.slug
    , c.sort_order
FROM (
    VALUES
    ('flooring', NULL::uuid, 'Ceramic Tiles', 'ceramic-tiles', 10)
    , ('flooring', NULL::uuid, 'Porcelain Tiles', 'porcelain-tiles', 20)
    , ('flooring', NULL::uuid, 'Vinyl Flooring', 'vinyl-flooring', 30)
    , ('flooring', NULL::uuid, 'Laminate Flooring', 'laminate-flooring', 40)
    , ('flooring', NULL::uuid, 'Timber Flooring', 'timber-flooring', 50)
    , ('flooring', NULL::uuid, 'Cement Screed', 'cement-screed', 60)
    , ('flooring', NULL::uuid, 'Carpet', 'carpet', 70)
    , ('ceiling', NULL::uuid, 'Plaster Ceiling', 'plaster-ceiling', 10)
    , ('ceiling', NULL::uuid, 'Gypsum Board', 'gypsum-board', 20)
    , ('ceiling', NULL::uuid, 'Grid Ceiling', 'grid-ceiling', 30)
    , ('ceiling', NULL::uuid, 'Timber Ceiling', 'timber-ceiling', 40)
    , ('ceiling', NULL::uuid, 'Ceiling Cornices', 'ceiling-cornices', 50)
    , ('walls-plastering', NULL::uuid, 'Cement', 'cement', 10)
    , ('walls-plastering', NULL::uuid, 'Bricks & Blocks', 'bricks-blocks', 20)
    , ('walls-plastering', NULL::uuid, 'Wall Plaster', 'wall-plaster', 30)
    , ('walls-plastering', NULL::uuid, 'Wall Tiles', 'wall-tiles', 40)
    , ('walls-plastering', NULL::uuid, 'Wallpaper', 'wallpaper', 50)
    , ('walls-plastering', NULL::uuid, 'Skimcoat', 'skimcoat', 60)
    , ('doors-windows', NULL::uuid, 'Timber Doors', 'timber-doors', 10)
    , ('doors-windows', NULL::uuid, 'Aluminium Doors', 'aluminium-doors', 20)
    , ('doors-windows', NULL::uuid, 'Glass Doors', 'glass-doors', 30)
    , ('doors-windows', NULL::uuid, 'Aluminium Windows', 'aluminium-windows', 40)
    , ('doors-windows', NULL::uuid, 'uPVC Windows', 'upvc-windows', 50)
    , ('doors-windows', NULL::uuid, 'Door Grilles', 'door-grilles', 60)
    , ('doors-windows', NULL::uuid, 'Window Grilles', 'window-grilles', 70)
    , ('electrical', NULL::uuid, 'Wiring & Cables', 'wiring-cables', 10)
    , ('electrical', NULL::uuid, 'Switches & Sockets', 'switches-sockets', 20)
    , ('electrical', NULL::uuid, 'Circuit Breakers', 'circuit-breakers', 30)
    , ('electrical', NULL::uuid, 'Conduits & Trunking', 'conduits-trunking', 40)
    , ('electrical', NULL::uuid, 'Distribution Boards', 'distribution-boards', 50)
    , ('plumbing', NULL::uuid, 'Pipes & Fittings', 'pipes-fittings', 10)
    , ('plumbing', NULL::uuid, 'Faucets & Mixers', 'faucets-mixers', 20)
    , ('plumbing', NULL::uuid, 'Water Tanks', 'water-tanks', 30)
    , ('plumbing', NULL::uuid, 'Water Heaters', 'water-heaters', 40)
    , ('plumbing', NULL::uuid, 'Drainage', 'drainage', 50)
    , ('painting-finishing', NULL::uuid, 'Interior Paint', 'interior-paint', 10)
    , ('painting-finishing', NULL::uuid, 'Exterior Paint', 'exterior-paint', 20)
    , ('painting-finishing', NULL::uuid, 'Primer & Sealer', 'primer-sealer', 30)
    , ('painting-finishing', NULL::uuid, 'Waterproofing', 'waterproofing', 40)
    , ('painting-finishing', NULL::uuid, 'Painting Tools', 'painting-tools', 50)
    , ('bathroom', NULL::uuid, 'Toilets & WC', 'toilets-wc', 10)
    , ('bathroom', NULL::uuid, 'Basins & Sinks', 'basins-sinks', 20)
    , ('bathroom', NULL::uuid, 'Shower Systems', 'shower-systems', 30)
    , ('bathroom', NULL::uuid, 'Bathtubs', 'bathtubs', 40)
    , ('bathroom', NULL::uuid, 'Bathroom Cabinets', 'bathroom-cabinets', 50)
) AS c (parent_slug, organization_id, name, slug, sort_order)
INNER JOIN categories
    AS p ON c.parent_slug = p.slug
AND p.organization_id IS NULL;

INSERT INTO attributes (organization_id, name, slug, type) VALUES
-- universal
(NULL, 'Material', 'material', 'select')
, (NULL, 'Color', 'color', 'select')
, (NULL, 'Finish', 'finish', 'select')
, (NULL, 'Length', 'length', 'select')
, (NULL, 'Width', 'width', 'select')
, (NULL, 'Height', 'height', 'select')
, (NULL, 'Thickness', 'thickness', 'select')
, (NULL, 'Diameter', 'diameter', 'select')
, (NULL, 'Weight', 'weight', 'select')
-- construction specific
, (NULL, 'Grade', 'grade', 'select')
, (NULL, 'Standard', 'standard', 'select')
, (NULL, 'Fire Rating', 'fire-rating', 'select')
, (NULL, 'Water Resistance', 'water-resistance', 'select')
, (NULL, 'Load Capacity', 'load-capacity', 'select')
, (NULL, 'Voltage', 'voltage', 'select')
, (NULL, 'Current Rating', 'current-rating', 'select')
, (NULL, 'IP Rating', 'ip-rating', 'select')
, (NULL, 'Pipe Size', 'pipe-size', 'select')
, (NULL, 'Coverage Area', 'coverage-area', 'select')
, (NULL, 'Tile Size', 'tile-size', 'select')
, (NULL, 'Cable Size', 'cable-size', 'select')
, (NULL, 'Texture', 'texture', 'select')
, (NULL, 'Slip Resistance', 'slip-resistance', 'select')
, (NULL, 'Cement Grade', 'cement-grade', 'select')
, (NULL, 'Unit of Measure', 'unit-of-measure', 'select');

INSERT INTO attribute_values (attribute_id, organization_id, value, label, sort_order) VALUES
-- Material (id: 1)
(1, NULL, 'ceramic', 'Ceramic', 10)
, (1, NULL, 'porcelain', 'Porcelain', 20)
, (1, NULL, 'timber', 'Timber', 30)
, (1, NULL, 'aluminium', 'Aluminium', 40)
, (1, NULL, 'upvc', 'uPVC', 50)
, (1, NULL, 'steel', 'Steel', 60)
, (1, NULL, 'stainless-steel', 'Stainless Steel', 70)
, (1, NULL, 'glass', 'Glass', 80)
, (1, NULL, 'concrete', 'Concrete', 90)
, (1, NULL, 'gypsum', 'Gypsum', 100)
, (1, NULL, 'vinyl', 'Vinyl', 110)
, (1, NULL, 'copper', 'Copper', 120)
, (1, NULL, 'pvc', 'PVC', 130)
, (1, NULL, 'marble', 'Marble', 140)
, (1, NULL, 'granite', 'Granite', 150)
, (1, NULL, 'cement', 'Cement', 160)
-- Finish (id: 3)
, (3, NULL, 'matte', 'Matte', 10)
, (3, NULL, 'gloss', 'Gloss', 20)
, (3, NULL, 'semi-gloss', 'Semi-Gloss', 30)
, (3, NULL, 'satin', 'Satin', 40)
, (3, NULL, 'polished', 'Polished', 50)
, (3, NULL, 'brushed', 'Brushed', 60)
, (3, NULL, 'textured', 'Textured', 70)
, (3, NULL, 'natural', 'Natural', 80)
, (3, NULL, 'powder-coated', 'Powder Coated', 90)
, (3, NULL, 'anodized', 'Anodized', 100)
-- Thickness (id: 7) in mm
, (7, NULL, '6mm', '6mm', 10)
, (7, NULL, '9mm', '9mm', 20)
, (7, NULL, '12mm', '12mm', 30)
, (7, NULL, '15mm', '15mm', 40)
, (7, NULL, '18mm', '18mm', 50)
, (7, NULL, '20mm', '20mm', 60)
, (7, NULL, '25mm', '25mm', 70)
, (7, NULL, '30mm', '30mm', 80)
-- Fire Rating (id: 12)
, (12, NULL, 'non-rated', 'Non-Rated', 10)
, (12, NULL, 'fr-30', '30 Minutes', 20)
, (12, NULL, 'fr-60', '60 Minutes', 30)
, (12, NULL, 'fr-90', '90 Minutes', 40)
, (12, NULL, 'fr-120', '120 Minutes', 50)
-- Water Resistance (id: 13)
, (13, NULL, 'non-waterproof', 'Non-Waterproof', 10)
, (13, NULL, 'water-resistant', 'Water Resistant', 20)
, (13, NULL, 'waterproof', 'Waterproof', 30)
, (13, NULL, 'fully-submersible', 'Fully Submersible', 40)
-- Voltage (id: 15)
, (15, NULL, '240v', '240V', 10)
, (15, NULL, '415v', '415V (3-Phase)', 20)
, (15, NULL, '12v', '12V', 30)
, (15, NULL, '24v', '24V', 40)
-- Current Rating (id: 16) in Ampere
, (16, NULL, '6a', '6A', 10)
, (16, NULL, '10a', '10A', 20)
, (16, NULL, '13a', '13A', 30)
, (16, NULL, '16a', '16A', 40)
, (16, NULL, '20a', '20A', 50)
, (16, NULL, '32a', '32A', 60)
, (16, NULL, '40a', '40A', 70)
, (16, NULL, '63a', '63A', 80)
, (16, NULL, '100a', '100A', 90)
-- IP Rating (id: 17)
, (17, NULL, 'ip20', 'IP20', 10)
, (17, NULL, 'ip44', 'IP44', 20)
, (17, NULL, 'ip54', 'IP54', 30)
, (17, NULL, 'ip65', 'IP65', 40)
, (17, NULL, 'ip66', 'IP66', 50)
, (17, NULL, 'ip67', 'IP67', 60)
, (17, NULL, 'ip68', 'IP68', 70)
-- Cable Size (id: 21) in mm²
, (21, NULL, '1.5mm2', '1.5mm²', 10)
, (21, NULL, '2.5mm2', '2.5mm²', 20)
, (21, NULL, '4mm2', '4mm²', 30)
, (21, NULL, '6mm2', '6mm²', 40)
, (21, NULL, '10mm2', '10mm²', 50)
, (21, NULL, '16mm2', '16mm²', 60)
, (21, NULL, '25mm2', '25mm²', 70)
, (21, NULL, '35mm2', '35mm²', 80)
, (21, NULL, '50mm2', '50mm²', 90)
-- Tile Size (id: 20) in mm
, (20, NULL, '300x300', '300 x 300mm', 10)
, (20, NULL, '300x600', '300 x 600mm', 20)
, (20, NULL, '600x600', '600 x 600mm', 30)
, (20, NULL, '600x1200', '600 x 1200mm', 40)
, (20, NULL, '800x800', '800 x 800mm', 50)
, (20, NULL, '800x1600', '800 x 1600mm', 60)
, (20, NULL, '1000x1000', '1000 x 1000mm', 70)
, (20, NULL, '1200x1200', '1200 x 1200mm', 80)
-- Pipe Size (id: 18) in inches
, (18, NULL, '0.5in', '1/2"', 10)
, (18, NULL, '0.75in', '3/4"', 20)
, (18, NULL, '1in', '1"', 30)
, (18, NULL, '1.25in', '1-1/4"', 40)
, (18, NULL, '1.5in', '1-1/2"', 50)
, (18, NULL, '2in', '2"', 60)
, (18, NULL, '3in', '3"', 70)
, (18, NULL, '4in', '4"', 80)
-- Slip Resistance (id: 23)
, (23, NULL, 'r9', 'R9', 10)
, (23, NULL, 'r10', 'R10', 20)
, (23, NULL, 'r11', 'R11', 30)
, (23, NULL, 'r12', 'R12', 40)
, (23, NULL, 'r13', 'R13', 50)
-- Cement Grade (id: 24)
, (24, NULL, 'opc-32.5', 'OPC 32.5', 10)
, (24, NULL, 'opc-42.5', 'OPC 42.5', 20)
, (24, NULL, 'opc-52.5', 'OPC 52.5', 30)
-- Unit of Measure (id: 25)
, (25, NULL, 'piece', 'Piece', 10)
, (25, NULL, 'box', 'Box', 20)
, (25, NULL, 'carton', 'Carton', 30)
, (25, NULL, 'roll', 'Roll', 40)
, (25, NULL, 'bag', 'Bag', 50)
, (25, NULL, 'kg', 'Kilogram (kg)', 60)
, (25, NULL, 'ton', 'Tonne', 70)
, (25, NULL, 'litre', 'Litre', 80)
, (25, NULL, 'meter', 'Metre (m)', 90)
, (25, NULL, 'sqm', 'Square Metre (m²)', 100)
, (25, NULL, 'set', 'Set', 110)
, (25, NULL, 'pair', 'Pair', 120);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM categories
WHERE organization_id IS NULL;

DELETE FROM attributes
WHERE organization_id IS NULL;

DELETE FROM attribute_values
WHERE organization_id IS NULL;
-- +goose StatementEnd
