services:
  postgres:
    image: postgres:18
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      APP_SYSTEM_PASSWORD: ${APP_SYSTEM_PASSWORD}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: ecomerce-cache
    network_mode: host
    ulimits:
      memlock: -1
    volumes:
      - dragonfly_data:/data
  garage:
    image: dxflrs/garage:v2.3.0
    container_name: ecommerce-storage
    command: /garage server --single-node --default-bucket
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      GARAGE_DEFAULT_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      GARAGE_DEFAULT_BUCKET: ${S3_BUCKET}
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/data:/var/lib/garage
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:v3.31.2
    container_name: ecommerce-imgproxy
    ports:
      - "8081:8080"
    environment:
      IMGPROXY_USE_S3: true
      IMGPROXY_ENDPOINT: http://garage:3900
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${S3_BUCKET}
      AWS_S3_ENDPOINT_USE_PATH_STYLE: true
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}

volumes:
  postgres_data:
  dragonfly_data:
