// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (
    organization_id
    , name
    , slug
    , type
) VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, slug, type
`

type CreateAttributeParams struct {
	OrganizationID *uuid.UUID `json:"organization_id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Type           string     `json:"type"`
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.Type,
	)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Type,
	)
	return i, err
}
