// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute_value.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAttributeValue = `-- name: CreateAttributeValue :one
INSERT INTO attribute_values (
    attribute_id
    , organization_id
    , value
    , label
    , sort_order
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, attribute_id, organization_id, value, label, sort_order
`

type CreateAttributeValueParams struct {
	AttributeID    int64      `json:"attribute_id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	Value          string     `json:"value"`
	Label          string     `json:"label"`
	SortOrder      int16      `json:"sort_order"`
}

func (q *Queries) CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error) {
	row := q.db.QueryRow(ctx, createAttributeValue,
		arg.AttributeID,
		arg.OrganizationID,
		arg.Value,
		arg.Label,
		arg.SortOrder,
	)
	var i AttributeValue
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.OrganizationID,
		&i.Value,
		&i.Label,
		&i.SortOrder,
	)
	return i, err
}
