// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createCart = `-- name: CreateCart :one
INSERT INTO
    carts (buyer_org_id)
VALUES
    ($1) ON CONFLICT (buyer_org_id) DO
UPDATE
SET
    buyer_org_id = EXCLUDED.buyer_org_id
RETURNING
    id, buyer_org_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, buyerOrgID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, buyerOrgID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.BuyerOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByBuyerOrgID = `-- name: GetCartByBuyerOrgID :one
SELECT
    id, buyer_org_id, created_at, updated_at
FROM
    carts
WHERE
    buyer_org_id = $1
`

func (q *Queries) GetCartByBuyerOrgID(ctx context.Context, buyerOrgID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByBuyerOrgID, buyerOrgID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.BuyerOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartDetails = `-- name: GetCartDetails :many
SELECT
    c.id AS cart_id,
    c.buyer_org_id,
    g.id AS cart_shop_group_id,
    g.merchant_org_id,
    merchant.name AS merchant_name,
    g.is_selected AS group_is_selected,
    g.subtotal,
    i.id AS cart_item_id,
    i.product_variant_id,
    i.quantity,
    i.unit_price,
    i.is_selected AS item_is_selected,
    p.id AS product_id,
    p.name AS product_name,
    p.slug AS product_slug,
    v.name AS variant_name,
    v.sku,
    v.price AS current_price,
    v.is_active AS variant_is_active,
    p.status AS product_status,
    COALESCE(thumbnail.asset_key, '') AS thumbnail_asset_key,
    COALESCE(thumbnail.source, '') AS thumbnail_source
FROM
    carts c
    JOIN cart_shop_groups g ON g.cart_id = c.id
    JOIN organizations merchant ON merchant.id = g.merchant_org_id
    JOIN cart_items i ON i.cart_shop_group_id = g.id
    JOIN product_variants v ON v.id = i.product_variant_id
    JOIN products p ON p.id = v.product_id
    LEFT JOIN LATERAL (
        SELECT
            pa.asset_key,
            CASE
                WHEN pa.product_variant_id = v.id THEN 'variant'::TEXT
                ELSE 'product'::TEXT
            END AS source
        FROM
            product_assets pa
        WHERE
            pa.product_id = p.id
            AND pa."type" = 'image'
            AND (
                pa.product_variant_id = v.id
                OR pa.product_variant_id IS NULL
            )
        ORDER BY
            CASE
                WHEN pa.product_variant_id = v.id THEN 0
                ELSE 1
            END,
            pa.is_primary DESC,
            pa.sort_order ASC,
            pa.id ASC
        LIMIT
            1
    ) thumbnail ON TRUE
WHERE
    c.buyer_org_id = $1
ORDER BY
    merchant.name,
    p.name,
    v.name
`

type GetCartDetailsRow struct {
	CartID            uuid.UUID       `json:"cart_id"`
	BuyerOrgID        uuid.UUID       `json:"buyer_org_id"`
	CartShopGroupID   uuid.UUID       `json:"cart_shop_group_id"`
	MerchantOrgID     uuid.UUID       `json:"merchant_org_id"`
	MerchantName      string          `json:"merchant_name"`
	GroupIsSelected   bool            `json:"group_is_selected"`
	Subtotal          decimal.Decimal `json:"subtotal"`
	CartItemID        uuid.UUID       `json:"cart_item_id"`
	ProductVariantID  uuid.UUID       `json:"product_variant_id"`
	Quantity          int16           `json:"quantity"`
	UnitPrice         decimal.Decimal `json:"unit_price"`
	ItemIsSelected    bool            `json:"item_is_selected"`
	ProductID         uuid.UUID       `json:"product_id"`
	ProductName       string          `json:"product_name"`
	ProductSlug       string          `json:"product_slug"`
	VariantName       string          `json:"variant_name"`
	Sku               string          `json:"sku"`
	CurrentPrice      decimal.Decimal `json:"current_price"`
	VariantIsActive   bool            `json:"variant_is_active"`
	ProductStatus     string          `json:"product_status"`
	ThumbnailAssetKey string          `json:"thumbnail_asset_key"`
	ThumbnailSource   string          `json:"thumbnail_source"`
}

func (q *Queries) GetCartDetails(ctx context.Context, buyerOrgID uuid.UUID) ([]GetCartDetailsRow, error) {
	rows, err := q.db.Query(ctx, getCartDetails, buyerOrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartDetailsRow{}
	for rows.Next() {
		var i GetCartDetailsRow
		if err := rows.Scan(
			&i.CartID,
			&i.BuyerOrgID,
			&i.CartShopGroupID,
			&i.MerchantOrgID,
			&i.MerchantName,
			&i.GroupIsSelected,
			&i.Subtotal,
			&i.CartItemID,
			&i.ProductVariantID,
			&i.Quantity,
			&i.UnitPrice,
			&i.ItemIsSelected,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSlug,
			&i.VariantName,
			&i.Sku,
			&i.CurrentPrice,
			&i.VariantIsActive,
			&i.ProductStatus,
			&i.ThumbnailAssetKey,
			&i.ThumbnailSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItemDetailsForBuyerOrg = `-- name: GetCartItemDetailsForBuyerOrg :one
SELECT
    i.id AS cart_item_id,
    i.product_variant_id,
    i.quantity,
    i.unit_price,
    i.is_selected AS item_is_selected,
    p.id AS product_id,
    p.name AS product_name,
    p.slug AS product_slug,
    v.name AS variant_name,
    v.sku,
    v.price AS current_price,
    v.is_active AS variant_is_active,
    p.status AS product_status
FROM
    cart_items i
    JOIN cart_shop_groups g ON g.id = i.cart_shop_group_id
    JOIN carts c ON c.id = g.cart_id
    JOIN product_variants v ON v.id = i.product_variant_id
    JOIN products p ON p.id = v.product_id
WHERE
    i.id = $1
    AND c.buyer_org_id = $2
`

type GetCartItemDetailsForBuyerOrgParams struct {
	CartItemID uuid.UUID `json:"cart_item_id"`
	BuyerOrgID uuid.UUID `json:"buyer_org_id"`
}

type GetCartItemDetailsForBuyerOrgRow struct {
	CartItemID       uuid.UUID       `json:"cart_item_id"`
	ProductVariantID uuid.UUID       `json:"product_variant_id"`
	Quantity         int16           `json:"quantity"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
	ItemIsSelected   bool            `json:"item_is_selected"`
	ProductID        uuid.UUID       `json:"product_id"`
	ProductName      string          `json:"product_name"`
	ProductSlug      string          `json:"product_slug"`
	VariantName      string          `json:"variant_name"`
	Sku              string          `json:"sku"`
	CurrentPrice     decimal.Decimal `json:"current_price"`
	VariantIsActive  bool            `json:"variant_is_active"`
	ProductStatus    string          `json:"product_status"`
}

func (q *Queries) GetCartItemDetailsForBuyerOrg(ctx context.Context, arg GetCartItemDetailsForBuyerOrgParams) (GetCartItemDetailsForBuyerOrgRow, error) {
	row := q.db.QueryRow(ctx, getCartItemDetailsForBuyerOrg, arg.CartItemID, arg.BuyerOrgID)
	var i GetCartItemDetailsForBuyerOrgRow
	err := row.Scan(
		&i.CartItemID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.ItemIsSelected,
		&i.ProductID,
		&i.ProductName,
		&i.ProductSlug,
		&i.VariantName,
		&i.Sku,
		&i.CurrentPrice,
		&i.VariantIsActive,
		&i.ProductStatus,
	)
	return i, err
}
