// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_checkout.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countSelectedCartItemsForCheckout = `-- name: CountSelectedCartItemsForCheckout :one
SELECT
    COUNT(*)
FROM
    carts c
    JOIN cart_shop_groups g ON g.cart_id = c.id
    JOIN cart_items i ON i.cart_shop_group_id = g.id
WHERE
    c.buyer_org_id = $1::UUID
    AND i.is_selected = TRUE
`

func (q *Queries) CountSelectedCartItemsForCheckout(ctx context.Context, buyerOrgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSelectedCartItemsForCheckout, buyerOrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSelectedCartItemsForCheckout = `-- name: DeleteSelectedCartItemsForCheckout :many
DELETE FROM
    cart_items i USING cart_shop_groups g,
    carts c
WHERE
    i.cart_shop_group_id = g.id
    AND g.cart_id = c.id
    AND c.buyer_org_id = $1::UUID
    AND i.is_selected = TRUE
    AND i.id = ANY($2::UUID [])
RETURNING
    i.id,
    i.cart_shop_group_id,
    i.product_variant_id
`

type DeleteSelectedCartItemsForCheckoutParams struct {
	BuyerOrgID  uuid.UUID   `json:"buyer_org_id"`
	CartItemIds []uuid.UUID `json:"cart_item_ids"`
}

type DeleteSelectedCartItemsForCheckoutRow struct {
	ID               uuid.UUID `json:"id"`
	CartShopGroupID  uuid.UUID `json:"cart_shop_group_id"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
}

func (q *Queries) DeleteSelectedCartItemsForCheckout(ctx context.Context, arg DeleteSelectedCartItemsForCheckoutParams) ([]DeleteSelectedCartItemsForCheckoutRow, error) {
	rows, err := q.db.Query(ctx, deleteSelectedCartItemsForCheckout, arg.BuyerOrgID, arg.CartItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteSelectedCartItemsForCheckoutRow{}
	for rows.Next() {
		var i DeleteSelectedCartItemsForCheckoutRow
		if err := rows.Scan(&i.ID, &i.CartShopGroupID, &i.ProductVariantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectedCartItemsForCheckout = `-- name: ListSelectedCartItemsForCheckout :many
SELECT
    c.id AS cart_id,
    g.id AS cart_shop_group_id,
    i.id AS cart_item_id,
    g.merchant_org_id,
    i.product_variant_id,
    i.quantity,
    i.unit_price AS cart_unit_price,
    pv.price AS current_unit_price,
    pv.track_inventory,
    pv.is_active AS variant_is_active,
    pv.sku,
    pv.name AS variant_name,
    p.id AS product_id,
    p.name AS product_name,
    p.slug AS product_slug,
    p.status AS product_status,
    COALESCE(
        (
        SELECT
            pa.asset_key
        FROM
            product_assets pa
        WHERE
            pa.product_id = p.id
            AND pa.type = 'image'
            AND (
                pa.product_variant_id = pv.id
                OR pa.product_variant_id IS NULL
            )
        ORDER BY
            (pa.product_variant_id = pv.id) DESC,
            pa.is_primary DESC,
            pa.sort_order,
            pa.id
        LIMIT
            1
        ),
        ''
    )::TEXT AS thumbnail_asset_key
FROM
    carts c
    JOIN cart_shop_groups g ON g.cart_id = c.id
    JOIN cart_items i ON i.cart_shop_group_id = g.id
    JOIN product_variants pv ON pv.id = i.product_variant_id
    JOIN products p ON p.id = pv.product_id
WHERE
    c.buyer_org_id = $1::UUID
    AND i.is_selected = TRUE
ORDER BY
    g.merchant_org_id,
    i.created_at,
    i.id
FOR UPDATE OF
    i
`

type ListSelectedCartItemsForCheckoutRow struct {
	CartID            uuid.UUID       `json:"cart_id"`
	CartShopGroupID   uuid.UUID       `json:"cart_shop_group_id"`
	CartItemID        uuid.UUID       `json:"cart_item_id"`
	MerchantOrgID     uuid.UUID       `json:"merchant_org_id"`
	ProductVariantID  uuid.UUID       `json:"product_variant_id"`
	Quantity          int16           `json:"quantity"`
	CartUnitPrice     decimal.Decimal `json:"cart_unit_price"`
	CurrentUnitPrice  decimal.Decimal `json:"current_unit_price"`
	TrackInventory    bool            `json:"track_inventory"`
	VariantIsActive   bool            `json:"variant_is_active"`
	Sku               string          `json:"sku"`
	VariantName       string          `json:"variant_name"`
	ProductID         uuid.UUID       `json:"product_id"`
	ProductName       string          `json:"product_name"`
	ProductSlug       string          `json:"product_slug"`
	ProductStatus     string          `json:"product_status"`
	ThumbnailAssetKey string          `json:"thumbnail_asset_key"`
}

func (q *Queries) ListSelectedCartItemsForCheckout(ctx context.Context, buyerOrgID uuid.UUID) ([]ListSelectedCartItemsForCheckoutRow, error) {
	rows, err := q.db.Query(ctx, listSelectedCartItemsForCheckout, buyerOrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSelectedCartItemsForCheckoutRow{}
	for rows.Next() {
		var i ListSelectedCartItemsForCheckoutRow
		if err := rows.Scan(
			&i.CartID,
			&i.CartShopGroupID,
			&i.CartItemID,
			&i.MerchantOrgID,
			&i.ProductVariantID,
			&i.Quantity,
			&i.CartUnitPrice,
			&i.CurrentUnitPrice,
			&i.TrackInventory,
			&i.VariantIsActive,
			&i.Sku,
			&i.VariantName,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSlug,
			&i.ProductStatus,
			&i.ThumbnailAssetKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
