// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_item.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const deleteCartItemForBuyerOrg = `-- name: DeleteCartItemForBuyerOrg :exec
DELETE FROM
    cart_items i USING cart_shop_groups g,
    carts c
WHERE
    i.id = $1
    AND i.cart_shop_group_id = g.id
    AND g.cart_id = c.id
    AND c.buyer_org_id = $2
`

type DeleteCartItemForBuyerOrgParams struct {
	CartItemID uuid.UUID `json:"cart_item_id"`
	BuyerOrgID uuid.UUID `json:"buyer_org_id"`
}

func (q *Queries) DeleteCartItemForBuyerOrg(ctx context.Context, arg DeleteCartItemForBuyerOrgParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemForBuyerOrg, arg.CartItemID, arg.BuyerOrgID)
	return err
}

const getCartItemForBuyerOrg = `-- name: GetCartItemForBuyerOrg :one
SELECT
    i.id, i.cart_shop_group_id, i.product_variant_id, i.quantity, i.unit_price, i.is_selected, i.created_at, i.updated_at,
    g.cart_id
FROM
    cart_items i
    JOIN cart_shop_groups g ON g.id = i.cart_shop_group_id
    JOIN carts c ON c.id = g.cart_id
WHERE
    i.id = $1
    AND c.buyer_org_id = $2
`

type GetCartItemForBuyerOrgParams struct {
	CartItemID uuid.UUID `json:"cart_item_id"`
	BuyerOrgID uuid.UUID `json:"buyer_org_id"`
}

type GetCartItemForBuyerOrgRow struct {
	ID               uuid.UUID       `json:"id"`
	CartShopGroupID  uuid.UUID       `json:"cart_shop_group_id"`
	ProductVariantID uuid.UUID       `json:"product_variant_id"`
	Quantity         int16           `json:"quantity"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
	IsSelected       bool            `json:"is_selected"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	CartID           uuid.UUID       `json:"cart_id"`
}

func (q *Queries) GetCartItemForBuyerOrg(ctx context.Context, arg GetCartItemForBuyerOrgParams) (GetCartItemForBuyerOrgRow, error) {
	row := q.db.QueryRow(ctx, getCartItemForBuyerOrg, arg.CartItemID, arg.BuyerOrgID)
	var i GetCartItemForBuyerOrgRow
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CartID,
	)
	return i, err
}

const setCartItemSelectedForBuyerOrg = `-- name: SetCartItemSelectedForBuyerOrg :one
UPDATE
    cart_items i
SET
    is_selected = $1::BOOLEAN
FROM
    cart_shop_groups g,
    carts c
WHERE
    i.id = $2
    AND i.cart_shop_group_id = g.id
    AND g.cart_id = c.id
    AND c.buyer_org_id = $3
RETURNING
    i.id, i.cart_shop_group_id, i.product_variant_id, i.quantity, i.unit_price, i.is_selected, i.created_at, i.updated_at
`

type SetCartItemSelectedForBuyerOrgParams struct {
	IsSelected bool      `json:"is_selected"`
	CartItemID uuid.UUID `json:"cart_item_id"`
	BuyerOrgID uuid.UUID `json:"buyer_org_id"`
}

func (q *Queries) SetCartItemSelectedForBuyerOrg(ctx context.Context, arg SetCartItemSelectedForBuyerOrgParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, setCartItemSelectedForBuyerOrg, arg.IsSelected, arg.CartItemID, arg.BuyerOrgID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCartItemsSelectedByGroupForBuyerOrg = `-- name: SetCartItemsSelectedByGroupForBuyerOrg :exec
UPDATE
    cart_items i
SET
    is_selected = $1::BOOLEAN
FROM
    cart_shop_groups g,
    carts c
WHERE
    i.cart_shop_group_id = g.id
    AND g.id = $2
    AND g.cart_id = c.id
    AND c.buyer_org_id = $3
`

type SetCartItemsSelectedByGroupForBuyerOrgParams struct {
	IsSelected      bool      `json:"is_selected"`
	CartShopGroupID uuid.UUID `json:"cart_shop_group_id"`
	BuyerOrgID      uuid.UUID `json:"buyer_org_id"`
}

func (q *Queries) SetCartItemsSelectedByGroupForBuyerOrg(ctx context.Context, arg SetCartItemsSelectedByGroupForBuyerOrgParams) error {
	_, err := q.db.Exec(ctx, setCartItemsSelectedByGroupForBuyerOrg, arg.IsSelected, arg.CartShopGroupID, arg.BuyerOrgID)
	return err
}

const updateCartItemQuantityForBuyerOrg = `-- name: UpdateCartItemQuantityForBuyerOrg :one
UPDATE
    cart_items i
SET
    quantity = $1::SMALLINT
FROM
    cart_shop_groups g,
    carts c
WHERE
    i.id = $2
    AND i.cart_shop_group_id = g.id
    AND g.cart_id = c.id
    AND c.buyer_org_id = $3
RETURNING
    i.id, i.cart_shop_group_id, i.product_variant_id, i.quantity, i.unit_price, i.is_selected, i.created_at, i.updated_at
`

type UpdateCartItemQuantityForBuyerOrgParams struct {
	Quantity   int16     `json:"quantity"`
	CartItemID uuid.UUID `json:"cart_item_id"`
	BuyerOrgID uuid.UUID `json:"buyer_org_id"`
}

func (q *Queries) UpdateCartItemQuantityForBuyerOrg(ctx context.Context, arg UpdateCartItemQuantityForBuyerOrgParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantityForBuyerOrg, arg.Quantity, arg.CartItemID, arg.BuyerOrgID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO
    cart_items (
        cart_shop_group_id,
        product_variant_id,
        quantity,
        unit_price,
        is_selected
    )
VALUES
    ($1, $2, $3, $4, TRUE) ON CONFLICT (cart_shop_group_id, product_variant_id) DO
UPDATE
SET
    quantity = cart_items.quantity + EXCLUDED.quantity,
    unit_price = EXCLUDED.unit_price,
    is_selected = TRUE
RETURNING
    id, cart_shop_group_id, product_variant_id, quantity, unit_price, is_selected, created_at, updated_at
`

type UpsertCartItemParams struct {
	CartShopGroupID  uuid.UUID       `json:"cart_shop_group_id"`
	ProductVariantID uuid.UUID       `json:"product_variant_id"`
	Quantity         int16           `json:"quantity"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartShopGroupID,
		arg.ProductVariantID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
