// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_shop_group.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteEmptyCartShopGroups = `-- name: DeleteEmptyCartShopGroups :exec
DELETE FROM
    cart_shop_groups g
WHERE
    g.cart_id = $1
    AND NOT EXISTS (
        SELECT
            1
        FROM
            cart_items i
        WHERE
            i.cart_shop_group_id = g.id
    )
`

func (q *Queries) DeleteEmptyCartShopGroups(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmptyCartShopGroups, cartID)
	return err
}

const getOrCreateCartShopGroup = `-- name: GetOrCreateCartShopGroup :one
INSERT INTO
    cart_shop_groups (cart_id, merchant_org_id)
VALUES
    ($1, $2) ON CONFLICT (cart_id, merchant_org_id) DO
UPDATE
SET
    merchant_org_id = EXCLUDED.merchant_org_id
RETURNING
    id, cart_id, merchant_org_id, is_selected, subtotal, created_at, updated_at
`

type GetOrCreateCartShopGroupParams struct {
	CartID        uuid.UUID `json:"cart_id"`
	MerchantOrgID uuid.UUID `json:"merchant_org_id"`
}

func (q *Queries) GetOrCreateCartShopGroup(ctx context.Context, arg GetOrCreateCartShopGroupParams) (CartShopGroup, error) {
	row := q.db.QueryRow(ctx, getOrCreateCartShopGroup, arg.CartID, arg.MerchantOrgID)
	var i CartShopGroup
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MerchantOrgID,
		&i.IsSelected,
		&i.Subtotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recalculateCartShopGroupSelection = `-- name: RecalculateCartShopGroupSelection :one
UPDATE
    cart_shop_groups g
SET
    is_selected = EXISTS (
        SELECT
            1
        FROM
            cart_items i
        WHERE
            i.cart_shop_group_id = g.id
    )
    AND NOT EXISTS (
        SELECT
            1
        FROM
            cart_items i
        WHERE
            i.cart_shop_group_id = g.id
            AND i.is_selected = FALSE
    )
WHERE
    g.id = $1
RETURNING
    id, cart_id, merchant_org_id, is_selected, subtotal, created_at, updated_at
`

func (q *Queries) RecalculateCartShopGroupSelection(ctx context.Context, id uuid.UUID) (CartShopGroup, error) {
	row := q.db.QueryRow(ctx, recalculateCartShopGroupSelection, id)
	var i CartShopGroup
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MerchantOrgID,
		&i.IsSelected,
		&i.Subtotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recalculateCartShopGroupSubtotal = `-- name: RecalculateCartShopGroupSubtotal :one
UPDATE
    cart_shop_groups g
SET
    subtotal = COALESCE(
        (
            SELECT
                SUM(i.unit_price * i.quantity)
            FROM
                cart_items i
            WHERE
                i.cart_shop_group_id = g.id
        ),
        0
    )
WHERE
    g.id = $1
RETURNING
    id, cart_id, merchant_org_id, is_selected, subtotal, created_at, updated_at
`

func (q *Queries) RecalculateCartShopGroupSubtotal(ctx context.Context, id uuid.UUID) (CartShopGroup, error) {
	row := q.db.QueryRow(ctx, recalculateCartShopGroupSubtotal, id)
	var i CartShopGroup
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MerchantOrgID,
		&i.IsSelected,
		&i.Subtotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCartShopGroupSelectedForBuyerOrg = `-- name: SetCartShopGroupSelectedForBuyerOrg :one
UPDATE
    cart_shop_groups g
SET
    is_selected = $1::BOOLEAN
FROM
    carts c
WHERE
    g.id = $2
    AND g.cart_id = c.id
    AND c.buyer_org_id = $3
RETURNING
    g.id, g.cart_id, g.merchant_org_id, g.is_selected, g.subtotal, g.created_at, g.updated_at
`

type SetCartShopGroupSelectedForBuyerOrgParams struct {
	IsSelected      bool      `json:"is_selected"`
	CartShopGroupID uuid.UUID `json:"cart_shop_group_id"`
	BuyerOrgID      uuid.UUID `json:"buyer_org_id"`
}

func (q *Queries) SetCartShopGroupSelectedForBuyerOrg(ctx context.Context, arg SetCartShopGroupSelectedForBuyerOrgParams) (CartShopGroup, error) {
	row := q.db.QueryRow(ctx, setCartShopGroupSelectedForBuyerOrg, arg.IsSelected, arg.CartShopGroupID, arg.BuyerOrgID)
	var i CartShopGroup
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MerchantOrgID,
		&i.IsSelected,
		&i.Subtotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
