// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_item.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const deleteCartItemForCustomerOrg = `-- name: DeleteCartItemForCustomerOrg :exec
DELETE FROM
    cart_items i USING cart_shop_groups g,
    carts c
WHERE
    i.id = $1
    AND i.cart_shop_group_id = g.id
    AND g.cart_id = c.id
    AND c.customer_org_id = $2
`

type DeleteCartItemForCustomerOrgParams struct {
	CartItemID    uuid.UUID `json:"cart_item_id"`
	CustomerOrgID uuid.UUID `json:"customer_org_id"`
}

func (q *Queries) DeleteCartItemForCustomerOrg(ctx context.Context, arg DeleteCartItemForCustomerOrgParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemForCustomerOrg, arg.CartItemID, arg.CustomerOrgID)
	return err
}

const getCartItemForCustomerOrg = `-- name: GetCartItemForCustomerOrg :one
SELECT
    i.id, i.cart_shop_group_id, i.product_variant_id, i.quantity, i.unit_price, i.is_selected, i.created_at, i.updated_at,
    g.cart_id
FROM
    cart_items i
    JOIN cart_shop_groups g ON g.id = i.cart_shop_group_id
    JOIN carts c ON c.id = g.cart_id
WHERE
    i.id = $1
    AND c.customer_org_id = $2
`

type GetCartItemForCustomerOrgParams struct {
	CartItemID    uuid.UUID `json:"cart_item_id"`
	CustomerOrgID uuid.UUID `json:"customer_org_id"`
}

type GetCartItemForCustomerOrgRow struct {
	ID               uuid.UUID       `json:"id"`
	CartShopGroupID  uuid.UUID       `json:"cart_shop_group_id"`
	ProductVariantID uuid.UUID       `json:"product_variant_id"`
	Quantity         int16           `json:"quantity"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
	IsSelected       bool            `json:"is_selected"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	CartID           uuid.UUID       `json:"cart_id"`
}

func (q *Queries) GetCartItemForCustomerOrg(ctx context.Context, arg GetCartItemForCustomerOrgParams) (GetCartItemForCustomerOrgRow, error) {
	row := q.db.QueryRow(ctx, getCartItemForCustomerOrg, arg.CartItemID, arg.CustomerOrgID)
	var i GetCartItemForCustomerOrgRow
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CartID,
	)
	return i, err
}

const setCartItemSelectedForCustomerOrg = `-- name: SetCartItemSelectedForCustomerOrg :one
UPDATE
    cart_items i
SET
    is_selected = $1::BOOLEAN
FROM
    cart_shop_groups g,
    carts c
WHERE
    i.id = $2
    AND i.cart_shop_group_id = g.id
    AND g.cart_id = c.id
    AND c.customer_org_id = $3
RETURNING
    i.id, i.cart_shop_group_id, i.product_variant_id, i.quantity, i.unit_price, i.is_selected, i.created_at, i.updated_at
`

type SetCartItemSelectedForCustomerOrgParams struct {
	IsSelected    bool      `json:"is_selected"`
	CartItemID    uuid.UUID `json:"cart_item_id"`
	CustomerOrgID uuid.UUID `json:"customer_org_id"`
}

func (q *Queries) SetCartItemSelectedForCustomerOrg(ctx context.Context, arg SetCartItemSelectedForCustomerOrgParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, setCartItemSelectedForCustomerOrg, arg.IsSelected, arg.CartItemID, arg.CustomerOrgID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCartItemsSelectedByGroupForCustomerOrg = `-- name: SetCartItemsSelectedByGroupForCustomerOrg :exec
UPDATE
    cart_items i
SET
    is_selected = $1::BOOLEAN
FROM
    cart_shop_groups g,
    carts c
WHERE
    i.cart_shop_group_id = g.id
    AND g.id = $2
    AND g.cart_id = c.id
    AND c.customer_org_id = $3
`

type SetCartItemsSelectedByGroupForCustomerOrgParams struct {
	IsSelected      bool      `json:"is_selected"`
	CartShopGroupID uuid.UUID `json:"cart_shop_group_id"`
	CustomerOrgID   uuid.UUID `json:"customer_org_id"`
}

func (q *Queries) SetCartItemsSelectedByGroupForCustomerOrg(ctx context.Context, arg SetCartItemsSelectedByGroupForCustomerOrgParams) error {
	_, err := q.db.Exec(ctx, setCartItemsSelectedByGroupForCustomerOrg, arg.IsSelected, arg.CartShopGroupID, arg.CustomerOrgID)
	return err
}

const updateCartItemQuantityForCustomerOrg = `-- name: UpdateCartItemQuantityForCustomerOrg :one
UPDATE
    cart_items i
SET
    quantity = $1::SMALLINT
FROM
    cart_shop_groups g,
    carts c
WHERE
    i.id = $2
    AND i.cart_shop_group_id = g.id
    AND g.cart_id = c.id
    AND c.customer_org_id = $3
RETURNING
    i.id, i.cart_shop_group_id, i.product_variant_id, i.quantity, i.unit_price, i.is_selected, i.created_at, i.updated_at
`

type UpdateCartItemQuantityForCustomerOrgParams struct {
	Quantity      int16     `json:"quantity"`
	CartItemID    uuid.UUID `json:"cart_item_id"`
	CustomerOrgID uuid.UUID `json:"customer_org_id"`
}

func (q *Queries) UpdateCartItemQuantityForCustomerOrg(ctx context.Context, arg UpdateCartItemQuantityForCustomerOrgParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantityForCustomerOrg, arg.Quantity, arg.CartItemID, arg.CustomerOrgID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO
    cart_items (
        cart_shop_group_id,
        product_variant_id,
        quantity,
        unit_price,
        is_selected
    )
VALUES
    ($1, $2, $3, $4, TRUE) ON CONFLICT (cart_shop_group_id, product_variant_id) DO
UPDATE
SET
    quantity = cart_items.quantity + EXCLUDED.quantity,
    unit_price = EXCLUDED.unit_price,
    is_selected = TRUE
RETURNING
    id, cart_shop_group_id, product_variant_id, quantity, unit_price, is_selected, created_at, updated_at
`

type UpsertCartItemParams struct {
	CartShopGroupID  uuid.UUID       `json:"cart_shop_group_id"`
	ProductVariantID uuid.UUID       `json:"product_variant_id"`
	Quantity         int16           `json:"quantity"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartShopGroupID,
		arg.ProductVariantID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartShopGroupID,
		&i.ProductVariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
