// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO
    categories (
        organization_id,
        parent_id,
        name,
        slug,
        description,
        sort_order
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING
    id, organization_id, parent_id, name, slug, description, sort_order, is_active, created_at
`

type CreateCategoryParams struct {
	OrganizationID *uuid.UUID `json:"organization_id"`
	ParentID       *uuid.UUID `json:"parent_id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Description    *string    `json:"description"`
	SortOrder      int16      `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.OrganizationID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    id,
    organization_id,
    parent_id,
    name,
    slug,
    description,
    sort_order,
    is_active,
    created_at
FROM
    categories
WHERE
    id = $1
ORDER BY
    id
LIMIT
    1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCategoryPath = `-- name: ListCategoryPath :many
WITH RECURSIVE ancestors AS (
    SELECT
        c.id,
        c.organization_id,
        c.parent_id,
        c.name,
        c.slug,
        c.description,
        c.sort_order,
        c.is_active,
        c.created_at,
        0 AS depth
    FROM
        categories c
    WHERE
        c.id = $1
    UNION ALL
    SELECT
        c.id,
        c.organization_id,
        c.parent_id,
        c.name,
        c.slug,
        c.description,
        c.sort_order,
        c.is_active,
        c.created_at,
        a.depth + 1 AS depth
    FROM
        categories c
        JOIN ancestors a ON a.parent_id = c.id
)
SELECT
    id,
    organization_id,
    parent_id,
    name,
    slug,
    description,
    sort_order,
    is_active,
    created_at
FROM
    ancestors
ORDER BY
    depth DESC
`

type ListCategoryPathRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	ParentID       *uuid.UUID `json:"parent_id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Description    *string    `json:"description"`
	SortOrder      int16      `json:"sort_order"`
	IsActive       bool       `json:"is_active"`
	CreatedAt      time.Time  `json:"created_at"`
}

func (q *Queries) ListCategoryPath(ctx context.Context, id uuid.UUID) ([]ListCategoryPathRow, error) {
	rows, err := q.db.Query(ctx, listCategoryPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryPathRow{}
	for rows.Next() {
		var i ListCategoryPathRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
