// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout_session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const cancelActiveCheckoutSessionsForBuyer = `-- name: CancelActiveCheckoutSessionsForBuyer :many
UPDATE
    checkout_sessions
SET
    "status" = 'cancelled',
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE
    buyer_org_id = $1::UUID
    AND buyer_member_id = $2::UUID
    AND "status" IN ('pending', 'reserved', 'payment_pending')
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

type CancelActiveCheckoutSessionsForBuyerParams struct {
	BuyerOrgID    uuid.UUID `json:"buyer_org_id"`
	BuyerMemberID uuid.UUID `json:"buyer_member_id"`
}

func (q *Queries) CancelActiveCheckoutSessionsForBuyer(ctx context.Context, arg CancelActiveCheckoutSessionsForBuyerParams) ([]CheckoutSession, error) {
	rows, err := q.db.Query(ctx, cancelActiveCheckoutSessionsForBuyer, arg.BuyerOrgID, arg.BuyerMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutSession{}
	for rows.Next() {
		var i CheckoutSession
		if err := rows.Scan(
			&i.ID,
			&i.BuyerCustomerID,
			&i.BuyerOrgID,
			&i.BuyerMemberID,
			&i.Status,
			&i.IdempotencyKey,
			&i.CheckoutFingerprint,
			&i.Subtotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.DiscountTotal,
			&i.GrandTotal,
			&i.Currency,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelCheckoutSession = `-- name: CancelCheckoutSession :one
UPDATE
    checkout_sessions
SET
    "status" = 'cancelled',
    cancelled_at = COALESCE(cancelled_at, NOW()),
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" IN ('pending', 'reserved', 'payment_pending')
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) CancelCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, cancelCheckoutSession, checkoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeCheckoutSession = `-- name: CompleteCheckoutSession :one
UPDATE
    checkout_sessions
SET
    "status" = 'completed',
    completed_at = COALESCE(completed_at, NOW()),
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" IN ('reserved', 'payment_pending')
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) CompleteCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, completeCheckoutSession, checkoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCheckoutSession = `-- name: CreateCheckoutSession :one
INSERT INTO
    checkout_sessions (
        buyer_customer_id,
        buyer_org_id,
        buyer_member_id,
        idempotency_key,
        checkout_fingerprint,
        subtotal,
        tax_total,
        shipping_total,
        discount_total,
        grand_total,
        currency,
        expires_at
    )
VALUES
    (
        $1::UUID,
        $2::UUID,
        $3::UUID,
        $4::TEXT,
        $5::TEXT,
        $6::NUMERIC,
        $7::NUMERIC,
        $8::NUMERIC,
        $9::NUMERIC,
        $10::NUMERIC,
        $11::TEXT,
        $12::TIMESTAMPTZ
    )
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

type CreateCheckoutSessionParams struct {
	BuyerCustomerID     uuid.UUID       `json:"buyer_customer_id"`
	BuyerOrgID          uuid.UUID       `json:"buyer_org_id"`
	BuyerMemberID       uuid.UUID       `json:"buyer_member_id"`
	IdempotencyKey      *string         `json:"idempotency_key"`
	CheckoutFingerprint string          `json:"checkout_fingerprint"`
	Subtotal            decimal.Decimal `json:"subtotal"`
	TaxTotal            decimal.Decimal `json:"tax_total"`
	ShippingTotal       decimal.Decimal `json:"shipping_total"`
	DiscountTotal       decimal.Decimal `json:"discount_total"`
	GrandTotal          decimal.Decimal `json:"grand_total"`
	Currency            string          `json:"currency"`
	ExpiresAt           *time.Time      `json:"expires_at"`
}

func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.BuyerCustomerID,
		arg.BuyerOrgID,
		arg.BuyerMemberID,
		arg.IdempotencyKey,
		arg.CheckoutFingerprint,
		arg.Subtotal,
		arg.TaxTotal,
		arg.ShippingTotal,
		arg.DiscountTotal,
		arg.GrandTotal,
		arg.Currency,
		arg.ExpiresAt,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireCheckoutSession = `-- name: ExpireCheckoutSession :one
UPDATE
    checkout_sessions
SET
    "status" = 'expired',
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" IN ('pending', 'reserved', 'payment_pending')
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) ExpireCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, expireCheckoutSession, checkoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCheckoutSessionForBuyer = `-- name: GetActiveCheckoutSessionForBuyer :one
SELECT
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
FROM
    checkout_sessions
WHERE
    buyer_org_id = $1::UUID
    AND buyer_member_id = $2::UUID
    AND "status" IN ('pending', 'reserved', 'payment_pending')
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    1
`

type GetActiveCheckoutSessionForBuyerParams struct {
	BuyerOrgID    uuid.UUID `json:"buyer_org_id"`
	BuyerMemberID uuid.UUID `json:"buyer_member_id"`
}

func (q *Queries) GetActiveCheckoutSessionForBuyer(ctx context.Context, arg GetActiveCheckoutSessionForBuyerParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getActiveCheckoutSessionForBuyer, arg.BuyerOrgID, arg.BuyerMemberID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCheckoutSessionForBuyerForUpdate = `-- name: GetActiveCheckoutSessionForBuyerForUpdate :one
SELECT
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
FROM
    checkout_sessions
WHERE
    buyer_org_id = $1::UUID
    AND buyer_member_id = $2::UUID
    AND "status" IN ('pending', 'reserved', 'payment_pending')
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    1
FOR UPDATE
`

type GetActiveCheckoutSessionForBuyerForUpdateParams struct {
	BuyerOrgID    uuid.UUID `json:"buyer_org_id"`
	BuyerMemberID uuid.UUID `json:"buyer_member_id"`
}

func (q *Queries) GetActiveCheckoutSessionForBuyerForUpdate(ctx context.Context, arg GetActiveCheckoutSessionForBuyerForUpdateParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getActiveCheckoutSessionForBuyerForUpdate, arg.BuyerOrgID, arg.BuyerMemberID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutSessionByID = `-- name: GetCheckoutSessionByID :one
SELECT
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
FROM
    checkout_sessions
WHERE
    id = $1::UUID
LIMIT
    1
`

func (q *Queries) GetCheckoutSessionByID(ctx context.Context, checkoutSessionID uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionByID, checkoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutSessionByIdempotencyKey = `-- name: GetCheckoutSessionByIdempotencyKey :one
SELECT
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
FROM
    checkout_sessions
WHERE
    buyer_org_id = $1::UUID
    AND buyer_member_id = $2::UUID
    AND idempotency_key = $3::TEXT
LIMIT
    1
`

type GetCheckoutSessionByIdempotencyKeyParams struct {
	BuyerOrgID     uuid.UUID `json:"buyer_org_id"`
	BuyerMemberID  uuid.UUID `json:"buyer_member_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetCheckoutSessionByIdempotencyKey(ctx context.Context, arg GetCheckoutSessionByIdempotencyKeyParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionByIdempotencyKey, arg.BuyerOrgID, arg.BuyerMemberID, arg.IdempotencyKey)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutSessionForBuyer = `-- name: GetCheckoutSessionForBuyer :one
SELECT
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
FROM
    checkout_sessions
WHERE
    id = $1::UUID
    AND buyer_org_id = $2::UUID
LIMIT
    1
`

type GetCheckoutSessionForBuyerParams struct {
	CheckoutSessionID uuid.UUID `json:"checkout_session_id"`
	BuyerOrgID        uuid.UUID `json:"buyer_org_id"`
}

func (q *Queries) GetCheckoutSessionForBuyer(ctx context.Context, arg GetCheckoutSessionForBuyerParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionForBuyer, arg.CheckoutSessionID, arg.BuyerOrgID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutSessionForUpdate = `-- name: GetCheckoutSessionForUpdate :one
SELECT
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
FROM
    checkout_sessions
WHERE
    id = $1::UUID
FOR UPDATE
`

func (q *Queries) GetCheckoutSessionForUpdate(ctx context.Context, checkoutSessionID uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionForUpdate, checkoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredActiveCheckoutSessionsForUpdate = `-- name: ListExpiredActiveCheckoutSessionsForUpdate :many
SELECT
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
FROM
    checkout_sessions
WHERE
    "status" IN ('pending', 'reserved', 'payment_pending')
    AND expires_at IS NOT NULL
    AND expires_at <= NOW()
ORDER BY
    expires_at,
    id
LIMIT
    $1::INT
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListExpiredActiveCheckoutSessionsForUpdate(ctx context.Context, pageLimit int32) ([]CheckoutSession, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveCheckoutSessionsForUpdate, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutSession{}
	for rows.Next() {
		var i CheckoutSession
		if err := rows.Scan(
			&i.ID,
			&i.BuyerCustomerID,
			&i.BuyerOrgID,
			&i.BuyerMemberID,
			&i.Status,
			&i.IdempotencyKey,
			&i.CheckoutFingerprint,
			&i.Subtotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.DiscountTotal,
			&i.GrandTotal,
			&i.Currency,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckoutSessionPaymentPending = `-- name: MarkCheckoutSessionPaymentPending :one
UPDATE
    checkout_sessions
SET
    "status" = 'payment_pending',
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" IN ('pending', 'reserved')
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) MarkCheckoutSessionPaymentPending(ctx context.Context, checkoutSessionID uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, markCheckoutSessionPaymentPending, checkoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCheckoutSessionReserved = `-- name: MarkCheckoutSessionReserved :one
UPDATE
    checkout_sessions
SET
    "status" = 'reserved',
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" = 'pending'
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) MarkCheckoutSessionReserved(ctx context.Context, checkoutSessionID uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, markCheckoutSessionReserved, checkoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCheckoutSessionTotals = `-- name: UpdateCheckoutSessionTotals :one
UPDATE
    checkout_sessions
SET
    subtotal = $1::NUMERIC,
    tax_total = $2::NUMERIC,
    shipping_total = $3::NUMERIC,
    discount_total = $4::NUMERIC,
    grand_total = $5::NUMERIC,
    updated_at = NOW()
WHERE
    id = $6::UUID
RETURNING
    id, buyer_customer_id, buyer_org_id, buyer_member_id, status, idempotency_key, checkout_fingerprint, subtotal, tax_total, shipping_total, discount_total, grand_total, currency, expires_at, completed_at, cancelled_at, created_at, updated_at
`

type UpdateCheckoutSessionTotalsParams struct {
	Subtotal          decimal.Decimal `json:"subtotal"`
	TaxTotal          decimal.Decimal `json:"tax_total"`
	ShippingTotal     decimal.Decimal `json:"shipping_total"`
	DiscountTotal     decimal.Decimal `json:"discount_total"`
	GrandTotal        decimal.Decimal `json:"grand_total"`
	CheckoutSessionID uuid.UUID       `json:"checkout_session_id"`
}

func (q *Queries) UpdateCheckoutSessionTotals(ctx context.Context, arg UpdateCheckoutSessionTotalsParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, updateCheckoutSessionTotals,
		arg.Subtotal,
		arg.TaxTotal,
		arg.ShippingTotal,
		arg.DiscountTotal,
		arg.GrandTotal,
		arg.CheckoutSessionID,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.Status,
		&i.IdempotencyKey,
		&i.CheckoutFingerprint,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
