// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO
    customers (identity_id, name, email)
VALUES
    ($1, $2, $3)
RETURNING
    id, identity_id, name, email, email_verified, image, created_at, updated_at
`

type CreateCustomerParams struct {
	IdentityID uuid.UUID `json:"identity_id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.IdentityID, arg.Name, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT
    id,
    identity_id,
    name,
    email,
    email_verified,
    image,
    created_at,
    updated_at
FROM
    customers
WHERE
    email = $1
ORDER BY
    id
LIMIT
    1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByIdentityID = `-- name: GetCustomerByIdentityID :one
SELECT
    id,
    identity_id,
    name,
    email,
    email_verified,
    image,
    created_at,
    updated_at
FROM
    customers
WHERE
    identity_id = $1
LIMIT
    1
`

func (q *Queries) GetCustomerByIdentityID(ctx context.Context, identityID uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByIdentityID, identityID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerWithCredential = `-- name: GetCustomerWithCredential :one
SELECT
    c.id,
    c.identity_id,
    c.name,
    c.email,
    ca.hashed_password
FROM
    customers c
    LEFT JOIN customer_accounts ca ON c.id = ca.customer_id
    AND ca.provider_id = 'credential'
WHERE
    c.email = $1
LIMIT
    1
`

type GetCustomerWithCredentialRow struct {
	ID             uuid.UUID `json:"id"`
	IdentityID     uuid.UUID `json:"identity_id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword *string   `json:"hashed_password"`
}

func (q *Queries) GetCustomerWithCredential(ctx context.Context, email string) (GetCustomerWithCredentialRow, error) {
	row := q.db.QueryRow(ctx, getCustomerWithCredential, email)
	var i GetCustomerWithCredentialRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
