// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    identity_id
    , name
    , email
) VALUES ($1, $2, $3)
RETURNING id, identity_id, name, email, email_verified, image, created_at, updated_at
`

type CreateCustomerParams struct {
	IdentityID uuid.UUID `json:"identity_id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.IdentityID, arg.Name, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT
    id
    , identity_id
    , name
    , email
    , email_verified
    , image
    , created_at
    , updated_at
FROM customers
WHERE email = $1
ORDER BY id
LIMIT 1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
