// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_account.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomerAccount = `-- name: CreateCustomerAccount :one
INSERT INTO customer_accounts (
    customer_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , hashed_password
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id
    , customer_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , created_at
    , updated_at
`

type CreateCustomerAccountParams struct {
	CustomerID            uuid.UUID  `json:"customer_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	HashedPassword        *string    `json:"hashed_password"`
}

type CreateCustomerAccountRow struct {
	ID                    uuid.UUID  `json:"id"`
	CustomerID            uuid.UUID  `json:"customer_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

func (q *Queries) CreateCustomerAccount(ctx context.Context, arg CreateCustomerAccountParams) (CreateCustomerAccountRow, error) {
	row := q.db.QueryRow(ctx, createCustomerAccount,
		arg.CustomerID,
		arg.AccountID,
		arg.ProviderID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.Scope,
		arg.IDToken,
		arg.HashedPassword,
	)
	var i CreateCustomerAccountRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerAccountByID = `-- name: GetCustomerAccountByID :one
SELECT
    id
    , customer_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , created_at
    , updated_at
FROM customer_accounts
WHERE customer_id = $1
ORDER BY id
LIMIT 1
`

type GetCustomerAccountByIDRow struct {
	ID                    uuid.UUID  `json:"id"`
	CustomerID            uuid.UUID  `json:"customer_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

func (q *Queries) GetCustomerAccountByID(ctx context.Context, customerID uuid.UUID) (GetCustomerAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerAccountByID, customerID)
	var i GetCustomerAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerHashedPassword = `-- name: GetCustomerHashedPassword :one
SELECT hashed_password
FROM customer_accounts
WHERE customer_id = $1 AND provider_id = $2
ORDER BY id
LIMIT 1
`

type GetCustomerHashedPasswordParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	ProviderID string    `json:"provider_id"`
}

func (q *Queries) GetCustomerHashedPassword(ctx context.Context, arg GetCustomerHashedPasswordParams) (*string, error) {
	row := q.db.QueryRow(ctx, getCustomerHashedPassword, arg.CustomerID, arg.ProviderID)
	var hashed_password *string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const updateCustomerAccount = `-- name: UpdateCustomerAccount :one
UPDATE customer_accounts
SET
    access_token = coalesce($2, access_token)
    , refresh_token = coalesce($3, refresh_token)
    , access_token_expires_at = coalesce($4, access_token_expires_at)
    , refresh_token_expires_at = coalesce($5, refresh_token_expires_at)
    , id_token = coalesce($6, id_token)
    , scope = coalesce($7, scope)
    , hashed_password = coalesce($8, hashed_password)
WHERE id = $1
RETURNING
    id
    , customer_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , created_at
    , updated_at
`

type UpdateCustomerAccountParams struct {
	ID                    uuid.UUID  `json:"id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	IDToken               *string    `json:"id_token"`
	Scope                 *string    `json:"scope"`
	HashedPassword        *string    `json:"hashed_password"`
}

type UpdateCustomerAccountRow struct {
	ID                    uuid.UUID  `json:"id"`
	CustomerID            uuid.UUID  `json:"customer_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateCustomerAccount(ctx context.Context, arg UpdateCustomerAccountParams) (UpdateCustomerAccountRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerAccount,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.IDToken,
		arg.Scope,
		arg.HashedPassword,
	)
	var i UpdateCustomerAccountRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
