// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO
    identities (TYPE)
VALUES
    ($1)
RETURNING
    id, type, created_at
`

func (q *Queries) CreateIdentity(ctx context.Context, type_ string) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity, type_)
	var i Identity
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}
