// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const confirmReservedInventory = `-- name: ConfirmReservedInventory :one
UPDATE
    inventories
SET
    quantity_on_hand = quantity_on_hand - $1::INT,
    quantity_reserved = quantity_reserved - $1::INT
WHERE
    product_variant_id = $2::UUID
    AND warehouse_id = $3::BIGINT
    AND $1::INT > 0
    AND EXISTS (
        SELECT
            1
        FROM
            product_variants pv
            JOIN warehouses w ON w.id = $3::BIGINT
        WHERE
            pv.id = $2::UUID
            AND pv.organization_id = $4::UUID
            AND w.organization_id = $4::UUID
    )
    AND quantity_reserved >= $1::INT
    AND quantity_on_hand >= $1::INT
RETURNING
    product_variant_id,
    warehouse_id,
    quantity_on_hand,
    quantity_reserved,
    quantity_available,
    low_stock_threshold,
    is_active
`

type ConfirmReservedInventoryParams struct {
	Quantity         int32     `json:"quantity"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
	MerchantOrgID    uuid.UUID `json:"merchant_org_id"`
}

func (q *Queries) ConfirmReservedInventory(ctx context.Context, arg ConfirmReservedInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, confirmReservedInventory,
		arg.Quantity,
		arg.ProductVariantID,
		arg.WarehouseID,
		arg.MerchantOrgID,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO
    inventories (
        product_variant_id,
        warehouse_id,
        quantity_on_hand,
        low_stock_threshold
    )
VALUES
    ($1, $2, $3, $4)
RETURNING
    product_variant_id, warehouse_id, quantity_on_hand, quantity_reserved, quantity_available, low_stock_threshold, is_active
`

type CreateInventoryParams struct {
	ProductVariantID  uuid.UUID `json:"product_variant_id"`
	WarehouseID       int64     `json:"warehouse_id"`
	QuantityOnHand    int32     `json:"quantity_on_hand"`
	LowStockThreshold *int32    `json:"low_stock_threshold"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory,
		arg.ProductVariantID,
		arg.WarehouseID,
		arg.QuantityOnHand,
		arg.LowStockThreshold,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}

const getInventoryByVariantAndWarehouseForOrganization = `-- name: GetInventoryByVariantAndWarehouseForOrganization :one
SELECT
    i.product_variant_id,
    i.warehouse_id,
    i.quantity_on_hand,
    i.quantity_reserved,
    i.quantity_available,
    i.low_stock_threshold,
    i.is_active,
    pv.product_id,
    pv.sku AS product_variant_sku,
    pv.name AS product_variant_name,
    p.name AS product_name,
    w.name AS warehouse_name
FROM
    inventories i
    JOIN product_variants pv ON pv.id = i.product_variant_id
    JOIN products p ON p.id = pv.product_id
    JOIN warehouses w ON w.id = i.warehouse_id
WHERE
    pv.organization_id = $1::UUID
    AND w.organization_id = $1::UUID
    AND i.product_variant_id = $2::UUID
    AND i.warehouse_id = $3::BIGINT
LIMIT
    1
`

type GetInventoryByVariantAndWarehouseForOrganizationParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
}

type GetInventoryByVariantAndWarehouseForOrganizationRow struct {
	ProductVariantID   uuid.UUID `json:"product_variant_id"`
	WarehouseID        int64     `json:"warehouse_id"`
	QuantityOnHand     int32     `json:"quantity_on_hand"`
	QuantityReserved   int32     `json:"quantity_reserved"`
	QuantityAvailable  *int32    `json:"quantity_available"`
	LowStockThreshold  *int32    `json:"low_stock_threshold"`
	IsActive           bool      `json:"is_active"`
	ProductID          uuid.UUID `json:"product_id"`
	ProductVariantSku  string    `json:"product_variant_sku"`
	ProductVariantName string    `json:"product_variant_name"`
	ProductName        string    `json:"product_name"`
	WarehouseName      string    `json:"warehouse_name"`
}

func (q *Queries) GetInventoryByVariantAndWarehouseForOrganization(ctx context.Context, arg GetInventoryByVariantAndWarehouseForOrganizationParams) (GetInventoryByVariantAndWarehouseForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getInventoryByVariantAndWarehouseForOrganization, arg.OrganizationID, arg.ProductVariantID, arg.WarehouseID)
	var i GetInventoryByVariantAndWarehouseForOrganizationRow
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
		&i.ProductID,
		&i.ProductVariantSku,
		&i.ProductVariantName,
		&i.ProductName,
		&i.WarehouseName,
	)
	return i, err
}

const getWarehouseVariantInventory = `-- name: GetWarehouseVariantInventory :one
SELECT
    i.product_variant_id,
    i.warehouse_id,
    i.quantity_on_hand,
    i.quantity_reserved,
    i.quantity_available,
    i.low_stock_threshold,
    i.is_active
FROM
    inventories i
    JOIN product_variants pv ON pv.id = i.product_variant_id
    JOIN warehouses w ON w.id = i.warehouse_id
WHERE
    pv.organization_id = $1::UUID
    AND w.organization_id = $1::UUID
    AND i.product_variant_id = $2::UUID
    AND i.warehouse_id = $3::BIGINT
ORDER BY
    i.product_variant_id
LIMIT
    1
`

type GetWarehouseVariantInventoryParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
}

func (q *Queries) GetWarehouseVariantInventory(ctx context.Context, arg GetWarehouseVariantInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getWarehouseVariantInventory, arg.OrganizationID, arg.ProductVariantID, arg.WarehouseID)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}

const listInventoryByOrganization = `-- name: ListInventoryByOrganization :many
SELECT
    i.product_variant_id,
    i.warehouse_id,
    i.quantity_on_hand,
    i.quantity_reserved,
    i.quantity_available,
    i.low_stock_threshold,
    i.is_active,
    pv.product_id,
    pv.sku AS product_variant_sku,
    pv.name AS product_variant_name,
    p.name AS product_name,
    w.name AS warehouse_name
FROM
    inventories i
    JOIN product_variants pv ON pv.id = i.product_variant_id
    JOIN products p ON p.id = pv.product_id
    JOIN warehouses w ON w.id = i.warehouse_id
WHERE
    pv.organization_id = $1::UUID
    AND w.organization_id = $1::UUID
    AND (
        NOT $2::BOOL
        OR (
            p.name,
            pv.name,
            w.name,
            i.product_variant_id,
            i.warehouse_id
        ) > (
            $3::TEXT,
            $4::TEXT,
            $5::TEXT,
            $6::UUID,
            $7::BIGINT
        )
    )
ORDER BY
    p.name,
    pv.name,
    w.name,
    i.product_variant_id,
    i.warehouse_id
LIMIT
    $8::INT
`

type ListInventoryByOrganizationParams struct {
	OrganizationID        uuid.UUID `json:"organization_id"`
	HasCursor             bool      `json:"has_cursor"`
	AfterProductName      string    `json:"after_product_name"`
	AfterVariantName      string    `json:"after_variant_name"`
	AfterWarehouseName    string    `json:"after_warehouse_name"`
	AfterProductVariantID uuid.UUID `json:"after_product_variant_id"`
	AfterWarehouseID      int64     `json:"after_warehouse_id"`
	PageLimit             int32     `json:"page_limit"`
}

type ListInventoryByOrganizationRow struct {
	ProductVariantID   uuid.UUID `json:"product_variant_id"`
	WarehouseID        int64     `json:"warehouse_id"`
	QuantityOnHand     int32     `json:"quantity_on_hand"`
	QuantityReserved   int32     `json:"quantity_reserved"`
	QuantityAvailable  *int32    `json:"quantity_available"`
	LowStockThreshold  *int32    `json:"low_stock_threshold"`
	IsActive           bool      `json:"is_active"`
	ProductID          uuid.UUID `json:"product_id"`
	ProductVariantSku  string    `json:"product_variant_sku"`
	ProductVariantName string    `json:"product_variant_name"`
	ProductName        string    `json:"product_name"`
	WarehouseName      string    `json:"warehouse_name"`
}

func (q *Queries) ListInventoryByOrganization(ctx context.Context, arg ListInventoryByOrganizationParams) ([]ListInventoryByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByOrganization,
		arg.OrganizationID,
		arg.HasCursor,
		arg.AfterProductName,
		arg.AfterVariantName,
		arg.AfterWarehouseName,
		arg.AfterProductVariantID,
		arg.AfterWarehouseID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryByOrganizationRow{}
	for rows.Next() {
		var i ListInventoryByOrganizationRow
		if err := rows.Scan(
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.QuantityOnHand,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.LowStockThreshold,
			&i.IsActive,
			&i.ProductID,
			&i.ProductVariantSku,
			&i.ProductVariantName,
			&i.ProductName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryByProduct = `-- name: ListInventoryByProduct :many
SELECT
    i.product_variant_id,
    i.warehouse_id,
    i.quantity_on_hand,
    i.quantity_reserved,
    i.quantity_available,
    i.low_stock_threshold,
    i.is_active,
    pv.product_id,
    pv.sku AS product_variant_sku,
    pv.name AS product_variant_name,
    p.name AS product_name,
    w.name AS warehouse_name
FROM
    inventories i
    JOIN product_variants pv ON pv.id = i.product_variant_id
    JOIN products p ON p.id = pv.product_id
    JOIN warehouses w ON w.id = i.warehouse_id
WHERE
    pv.organization_id = $1::UUID
    AND w.organization_id = $1::UUID
    AND pv.product_id = $2::UUID
ORDER BY
    pv.name,
    w.name
`

type ListInventoryByProductParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProductID      uuid.UUID `json:"product_id"`
}

type ListInventoryByProductRow struct {
	ProductVariantID   uuid.UUID `json:"product_variant_id"`
	WarehouseID        int64     `json:"warehouse_id"`
	QuantityOnHand     int32     `json:"quantity_on_hand"`
	QuantityReserved   int32     `json:"quantity_reserved"`
	QuantityAvailable  *int32    `json:"quantity_available"`
	LowStockThreshold  *int32    `json:"low_stock_threshold"`
	IsActive           bool      `json:"is_active"`
	ProductID          uuid.UUID `json:"product_id"`
	ProductVariantSku  string    `json:"product_variant_sku"`
	ProductVariantName string    `json:"product_variant_name"`
	ProductName        string    `json:"product_name"`
	WarehouseName      string    `json:"warehouse_name"`
}

func (q *Queries) ListInventoryByProduct(ctx context.Context, arg ListInventoryByProductParams) ([]ListInventoryByProductRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByProduct, arg.OrganizationID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryByProductRow{}
	for rows.Next() {
		var i ListInventoryByProductRow
		if err := rows.Scan(
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.QuantityOnHand,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.LowStockThreshold,
			&i.IsActive,
			&i.ProductID,
			&i.ProductVariantSku,
			&i.ProductVariantName,
			&i.ProductName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryByVariant = `-- name: ListInventoryByVariant :many
SELECT
    i.product_variant_id,
    i.warehouse_id,
    i.quantity_on_hand,
    i.quantity_reserved,
    i.quantity_available,
    i.low_stock_threshold,
    i.is_active,
    pv.product_id,
    pv.sku AS product_variant_sku,
    pv.name AS product_variant_name,
    p.name AS product_name,
    w.name AS warehouse_name
FROM
    inventories i
    JOIN product_variants pv ON pv.id = i.product_variant_id
    JOIN products p ON p.id = pv.product_id
    JOIN warehouses w ON w.id = i.warehouse_id
WHERE
    pv.organization_id = $1::UUID
    AND w.organization_id = $1::UUID
    AND i.product_variant_id = $2::UUID
ORDER BY
    w.name
`

type ListInventoryByVariantParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
}

type ListInventoryByVariantRow struct {
	ProductVariantID   uuid.UUID `json:"product_variant_id"`
	WarehouseID        int64     `json:"warehouse_id"`
	QuantityOnHand     int32     `json:"quantity_on_hand"`
	QuantityReserved   int32     `json:"quantity_reserved"`
	QuantityAvailable  *int32    `json:"quantity_available"`
	LowStockThreshold  *int32    `json:"low_stock_threshold"`
	IsActive           bool      `json:"is_active"`
	ProductID          uuid.UUID `json:"product_id"`
	ProductVariantSku  string    `json:"product_variant_sku"`
	ProductVariantName string    `json:"product_variant_name"`
	ProductName        string    `json:"product_name"`
	WarehouseName      string    `json:"warehouse_name"`
}

func (q *Queries) ListInventoryByVariant(ctx context.Context, arg ListInventoryByVariantParams) ([]ListInventoryByVariantRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByVariant, arg.OrganizationID, arg.ProductVariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryByVariantRow{}
	for rows.Next() {
		var i ListInventoryByVariantRow
		if err := rows.Scan(
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.QuantityOnHand,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.LowStockThreshold,
			&i.IsActive,
			&i.ProductID,
			&i.ProductVariantSku,
			&i.ProductVariantName,
			&i.ProductName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryCandidatesForCheckoutItem = `-- name: ListInventoryCandidatesForCheckoutItem :many
SELECT
    i.product_variant_id,
    i.warehouse_id,
    i.quantity_on_hand,
    i.quantity_reserved,
    i.quantity_available,
    i.low_stock_threshold,
    i.is_active
FROM
    inventories i
    JOIN product_variants pv ON pv.id = i.product_variant_id
    JOIN warehouses w ON w.id = i.warehouse_id
WHERE
    i.product_variant_id = $1::UUID
    AND pv.organization_id = $2::UUID
    AND w.organization_id = $2::UUID
    AND i.is_active = TRUE
    AND w.is_active = TRUE
    AND i.quantity_on_hand - i.quantity_reserved >= $3::INT
ORDER BY
    i.quantity_available DESC,
    i.warehouse_id
LIMIT
    $4::INT
`

type ListInventoryCandidatesForCheckoutItemParams struct {
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	MerchantOrgID    uuid.UUID `json:"merchant_org_id"`
	Quantity         int32     `json:"quantity"`
	PageLimit        int32     `json:"page_limit"`
}

func (q *Queries) ListInventoryCandidatesForCheckoutItem(ctx context.Context, arg ListInventoryCandidatesForCheckoutItemParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listInventoryCandidatesForCheckoutItem,
		arg.ProductVariantID,
		arg.MerchantOrgID,
		arg.Quantity,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.QuantityOnHand,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.LowStockThreshold,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReservedInventory = `-- name: ReleaseReservedInventory :one
UPDATE
    inventories
SET
    quantity_reserved = quantity_reserved - $1::INT
WHERE
    product_variant_id = $2::UUID
    AND warehouse_id = $3::BIGINT
    AND $1::INT > 0
    AND EXISTS (
        SELECT
            1
        FROM
            product_variants pv
            JOIN warehouses w ON w.id = $3::BIGINT
        WHERE
            pv.id = $2::UUID
            AND pv.organization_id = $4::UUID
            AND w.organization_id = $4::UUID
    )
    AND quantity_reserved >= $1::INT
RETURNING
    product_variant_id,
    warehouse_id,
    quantity_on_hand,
    quantity_reserved,
    quantity_available,
    low_stock_threshold,
    is_active
`

type ReleaseReservedInventoryParams struct {
	Quantity         int32     `json:"quantity"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
	MerchantOrgID    uuid.UUID `json:"merchant_org_id"`
}

func (q *Queries) ReleaseReservedInventory(ctx context.Context, arg ReleaseReservedInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, releaseReservedInventory,
		arg.Quantity,
		arg.ProductVariantID,
		arg.WarehouseID,
		arg.MerchantOrgID,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}

const reserveInventoryForCheckout = `-- name: ReserveInventoryForCheckout :one
UPDATE
    inventories
SET
    quantity_reserved = quantity_reserved + $1::INT
WHERE
    product_variant_id = $2::UUID
    AND warehouse_id = $3::BIGINT
    AND $1::INT > 0
    AND is_active = TRUE
    AND EXISTS (
        SELECT
            1
        FROM
            product_variants pv
            JOIN warehouses w ON w.id = $3::BIGINT
        WHERE
            pv.id = $2::UUID
            AND pv.organization_id = $4::UUID
            AND w.organization_id = $4::UUID
    )
    AND quantity_on_hand - quantity_reserved >= $1::INT
RETURNING
    product_variant_id,
    warehouse_id,
    quantity_on_hand,
    quantity_reserved,
    quantity_available,
    low_stock_threshold,
    is_active
`

type ReserveInventoryForCheckoutParams struct {
	Quantity         int32     `json:"quantity"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
	MerchantOrgID    uuid.UUID `json:"merchant_org_id"`
}

func (q *Queries) ReserveInventoryForCheckout(ctx context.Context, arg ReserveInventoryForCheckoutParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, reserveInventoryForCheckout,
		arg.Quantity,
		arg.ProductVariantID,
		arg.WarehouseID,
		arg.MerchantOrgID,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}

const upsertInventory = `-- name: UpsertInventory :one
WITH variant AS (
    SELECT
        id
    FROM
        product_variants
    WHERE
        id = $4::UUID
        AND organization_id = $5::UUID
),
warehouse AS (
    SELECT
        id
    FROM
        warehouses
    WHERE
        id = $6::BIGINT
        AND organization_id = $5::UUID
)
INSERT INTO
    inventories (
        product_variant_id,
        warehouse_id,
        quantity_on_hand,
        low_stock_threshold,
        is_active
    )
SELECT
    variant.id,
    warehouse.id,
    $1::INT,
    $2::INT,
    $3::BOOL
FROM
    variant,
    warehouse
ON CONFLICT (product_variant_id, warehouse_id) DO UPDATE
SET
    quantity_on_hand = EXCLUDED.quantity_on_hand,
    low_stock_threshold = EXCLUDED.low_stock_threshold,
    is_active = EXCLUDED.is_active
RETURNING
    product_variant_id,
    warehouse_id,
    quantity_on_hand,
    quantity_reserved,
    quantity_available,
    low_stock_threshold,
    is_active
`

type UpsertInventoryParams struct {
	QuantityOnHand    int32     `json:"quantity_on_hand"`
	LowStockThreshold *int32    `json:"low_stock_threshold"`
	IsActive          bool      `json:"is_active"`
	ProductVariantID  uuid.UUID `json:"product_variant_id"`
	OrganizationID    uuid.UUID `json:"organization_id"`
	WarehouseID       int64     `json:"warehouse_id"`
}

// If either ID does not belong to the organization, the SELECT below returns no
// rows. sqlc maps that empty RETURNING result to ErrNotFound for the handler.
func (q *Queries) UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, upsertInventory,
		arg.QuantityOnHand,
		arg.LowStockThreshold,
		arg.IsActive,
		arg.ProductVariantID,
		arg.OrganizationID,
		arg.WarehouseID,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}
