// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_reservation.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelInventoryReservation = `-- name: CancelInventoryReservation :one
UPDATE
    inventory_reservations
SET
    "status" = 'cancelled',
    released_at = COALESCE(released_at, NOW())
WHERE
    id = $1::UUID
    AND "status" = 'active'
RETURNING
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
`

func (q *Queries) CancelInventoryReservation(ctx context.Context, reservationID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, cancelInventoryReservation, reservationID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const confirmInventoryReservation = `-- name: ConfirmInventoryReservation :one
UPDATE
    inventory_reservations
SET
    "status" = 'confirmed',
    confirmed_at = COALESCE(confirmed_at, NOW())
WHERE
    id = $1::UUID
    AND "status" = 'active'
RETURNING
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
`

func (q *Queries) ConfirmInventoryReservation(ctx context.Context, reservationID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, confirmInventoryReservation, reservationID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInventoryReservation = `-- name: CreateInventoryReservation :one
INSERT INTO
    inventory_reservations (
        checkout_session_id,
        order_id,
        buyer_org_id,
        merchant_org_id,
        expires_at
    )
VALUES
    (
        $1::UUID,
        $2::UUID,
        $3::UUID,
        $4::UUID,
        $5::TIMESTAMPTZ
    )
RETURNING
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
`

type CreateInventoryReservationParams struct {
	CheckoutSessionID uuid.UUID `json:"checkout_session_id"`
	OrderID           uuid.UUID `json:"order_id"`
	BuyerOrgID        uuid.UUID `json:"buyer_org_id"`
	MerchantOrgID     uuid.UUID `json:"merchant_org_id"`
	ExpiresAt         time.Time `json:"expires_at"`
}

func (q *Queries) CreateInventoryReservation(ctx context.Context, arg CreateInventoryReservationParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, createInventoryReservation,
		arg.CheckoutSessionID,
		arg.OrderID,
		arg.BuyerOrgID,
		arg.MerchantOrgID,
		arg.ExpiresAt,
	)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInventoryReservationItem = `-- name: CreateInventoryReservationItem :one
INSERT INTO
    inventory_reservation_items (
        reservation_id,
        order_item_id,
        product_variant_id,
        warehouse_id,
        quantity
    )
VALUES
    (
        $1::UUID,
        $2::UUID,
        $3::UUID,
        $4::BIGINT,
        $5::INT
    )
RETURNING
    id, reservation_id, order_item_id, product_variant_id, warehouse_id, quantity, created_at
`

type CreateInventoryReservationItemParams struct {
	ReservationID    uuid.UUID `json:"reservation_id"`
	OrderItemID      uuid.UUID `json:"order_item_id"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
	Quantity         int32     `json:"quantity"`
}

func (q *Queries) CreateInventoryReservationItem(ctx context.Context, arg CreateInventoryReservationItemParams) (InventoryReservationItem, error) {
	row := q.db.QueryRow(ctx, createInventoryReservationItem,
		arg.ReservationID,
		arg.OrderItemID,
		arg.ProductVariantID,
		arg.WarehouseID,
		arg.Quantity,
	)
	var i InventoryReservationItem
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.OrderItemID,
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const expireInventoryReservation = `-- name: ExpireInventoryReservation :one
UPDATE
    inventory_reservations
SET
    "status" = 'expired',
    released_at = COALESCE(released_at, NOW())
WHERE
    id = $1::UUID
    AND "status" = 'active'
RETURNING
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
`

func (q *Queries) ExpireInventoryReservation(ctx context.Context, reservationID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, expireInventoryReservation, reservationID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveInventoryReservationByOrderForUpdate = `-- name: GetActiveInventoryReservationByOrderForUpdate :one
SELECT
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
FROM
    inventory_reservations
WHERE
    order_id = $1::UUID
    AND "status" = 'active'
FOR UPDATE
`

func (q *Queries) GetActiveInventoryReservationByOrderForUpdate(ctx context.Context, orderID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getActiveInventoryReservationByOrderForUpdate, orderID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInventoryReservationByID = `-- name: GetInventoryReservationByID :one
SELECT
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
FROM
    inventory_reservations
WHERE
    id = $1::UUID
LIMIT
    1
`

func (q *Queries) GetInventoryReservationByID(ctx context.Context, reservationID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getInventoryReservationByID, reservationID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInventoryReservationForUpdate = `-- name: GetInventoryReservationForUpdate :one
SELECT
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
FROM
    inventory_reservations
WHERE
    id = $1::UUID
FOR UPDATE
`

func (q *Queries) GetInventoryReservationForUpdate(ctx context.Context, reservationID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getInventoryReservationForUpdate, reservationID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredActiveInventoryReservationsForUpdate = `-- name: ListExpiredActiveInventoryReservationsForUpdate :many
SELECT
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
FROM
    inventory_reservations
WHERE
    "status" = 'active'
    AND expires_at <= NOW()
ORDER BY
    expires_at,
    id
LIMIT
    $1::INT
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListExpiredActiveInventoryReservationsForUpdate(ctx context.Context, pageLimit int32) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveInventoryReservationsForUpdate, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReservation{}
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.OrderID,
			&i.BuyerOrgID,
			&i.MerchantOrgID,
			&i.Status,
			&i.ExpiresAt,
			&i.ConfirmedAt,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryReservationItems = `-- name: ListInventoryReservationItems :many
SELECT
    id, reservation_id, order_item_id, product_variant_id, warehouse_id, quantity, created_at
FROM
    inventory_reservation_items
WHERE
    reservation_id = $1::UUID
ORDER BY
    created_at,
    id
`

func (q *Queries) ListInventoryReservationItems(ctx context.Context, reservationID uuid.UUID) ([]InventoryReservationItem, error) {
	rows, err := q.db.Query(ctx, listInventoryReservationItems, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReservationItem{}
	for rows.Next() {
		var i InventoryReservationItem
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.OrderItemID,
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryReservationItemsByCheckoutSession = `-- name: ListInventoryReservationItemsByCheckoutSession :many
SELECT
    iri.id, iri.reservation_id, iri.order_item_id, iri.product_variant_id, iri.warehouse_id, iri.quantity, iri.created_at
FROM
    inventory_reservation_items iri
    JOIN inventory_reservations ir ON ir.id = iri.reservation_id
WHERE
    ir.checkout_session_id = $1::UUID
ORDER BY
    ir.created_at,
    iri.created_at,
    iri.id
`

func (q *Queries) ListInventoryReservationItemsByCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) ([]InventoryReservationItem, error) {
	rows, err := q.db.Query(ctx, listInventoryReservationItemsByCheckoutSession, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReservationItem{}
	for rows.Next() {
		var i InventoryReservationItem
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.OrderItemID,
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryReservationsByCheckoutSession = `-- name: ListInventoryReservationsByCheckoutSession :many
SELECT
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
FROM
    inventory_reservations
WHERE
    checkout_session_id = $1::UUID
ORDER BY
    created_at,
    id
`

func (q *Queries) ListInventoryReservationsByCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) ([]InventoryReservation, error) {
	rows, err := q.db.Query(ctx, listInventoryReservationsByCheckoutSession, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryReservation{}
	for rows.Next() {
		var i InventoryReservation
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.OrderID,
			&i.BuyerOrgID,
			&i.MerchantOrgID,
			&i.Status,
			&i.ExpiresAt,
			&i.ConfirmedAt,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseInventoryReservation = `-- name: ReleaseInventoryReservation :one
UPDATE
    inventory_reservations
SET
    "status" = 'released',
    released_at = COALESCE(released_at, NOW())
WHERE
    id = $1::UUID
    AND "status" = 'active'
RETURNING
    id, checkout_session_id, order_id, buyer_org_id, merchant_org_id, status, expires_at, confirmed_at, released_at, created_at
`

func (q *Queries) ReleaseInventoryReservation(ctx context.Context, reservationID uuid.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, releaseInventoryReservation, reservationID)
	var i InventoryReservation
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.OrderID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}
