// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (
    product_variant_id
    , warehouse_id
    , quantity_on_hand
    , low_stock_threshold
) VALUES ($1, $2, $3, $4)
RETURNING product_variant_id, warehouse_id, quantity_on_hand, quantity_reserved, quantity_available, low_stock_threshold, is_active
`

type CreateInventoryParams struct {
	ProductVariantID  uuid.UUID `json:"product_variant_id"`
	WarehouseID       int64     `json:"warehouse_id"`
	QuantityOnHand    int32     `json:"quantity_on_hand"`
	LowStockThreshold *int32    `json:"low_stock_threshold"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory,
		arg.ProductVariantID,
		arg.WarehouseID,
		arg.QuantityOnHand,
		arg.LowStockThreshold,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}

const getWarehouseVariantInventory = `-- name: GetWarehouseVariantInventory :one
SELECT
    product_variant_id
    , warehouse_id
    , quantity_on_hand
    , quantity_reserved
    , quantity_available
    , low_stock_threshold
    , is_active
FROM inventories
WHERE product_variant_id = $1 AND warehouse_id = $2
ORDER BY product_variant_id
LIMIT 1
`

type GetWarehouseVariantInventoryParams struct {
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
}

func (q *Queries) GetWarehouseVariantInventory(ctx context.Context, arg GetWarehouseVariantInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getWarehouseVariantInventory, arg.ProductVariantID, arg.WarehouseID)
	var i Inventory
	err := row.Scan(
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.LowStockThreshold,
		&i.IsActive,
	)
	return i, err
}
