// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (
    identity_id
    , organization_id
) VALUES ($1, $2)
RETURNING id, identity_id, organization_id, created_at
`

type CreateMemberParams struct {
	IdentityID     uuid.UUID `json:"identity_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.IdentityID, arg.OrganizationID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}
