// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member_role.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignRoleToMember = `-- name: AssignRoleToMember :exec
INSERT INTO member_roles (
    member_id
    , role_id
    , assigned_by
) VALUES ($1, $2, $3)
`

type AssignRoleToMemberParams struct {
	MemberID   uuid.UUID  `json:"member_id"`
	RoleID     int16      `json:"role_id"`
	AssignedBy *uuid.UUID `json:"assigned_by"`
}

func (q *Queries) AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error {
	_, err := q.db.Exec(ctx, assignRoleToMember, arg.MemberID, arg.RoleID, arg.AssignedBy)
	return err
}
