// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countPlatformAdmins = `-- name: CountPlatformAdmins :one
SELECT
    COUNT(*)
FROM
    members m
    JOIN organizations o ON o.id = m.organization_id
WHERE
    o.type = 'platform'
`

func (q *Queries) CountPlatformAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO
    members (identity_id, organization_id)
VALUES
    ($1, $2)
RETURNING
    id, identity_id, organization_id, created_at
`

type CreateMemberParams struct {
	IdentityID     uuid.UUID `json:"identity_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.IdentityID, arg.OrganizationID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberByIdentityID = `-- name: GetMemberByIdentityID :one
SELECT
    id,
    identity_id,
    organization_id,
    created_at
FROM
    members
WHERE
    identity_id = $1
ORDER BY
    created_at ASC
LIMIT
    1
`

func (q *Queries) GetMemberByIdentityID(ctx context.Context, identityID uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByIdentityID, identityID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}
