// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Address struct {
	ID                uuid.UUID `json:"id"`
	OrganizationID    uuid.UUID `json:"organization_id"`
	Type              string    `json:"type"`
	Label             string    `json:"label"`
	Line1             string    `json:"line1"`
	Line2             *string   `json:"line2"`
	PostalCode        string    `json:"postal_code"`
	City              string    `json:"city"`
	State             string    `json:"state"`
	Country           string    `json:"country"`
	IsDefaultShipping bool      `json:"is_default_shipping"`
	IsDefaultBilling  bool      `json:"is_default_billing"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Attribute struct {
	ID             int64      `json:"id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Type           string     `json:"type"`
}

type AttributeValue struct {
	ID             int64      `json:"id"`
	AttributeID    int64      `json:"attribute_id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	Value          string     `json:"value"`
	Label          string     `json:"label"`
	SortOrder      int16      `json:"sort_order"`
}

type Cart struct {
	ID         uuid.UUID `json:"id"`
	BuyerOrgID uuid.UUID `json:"buyer_org_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CartItem struct {
	ID               uuid.UUID       `json:"id"`
	CartShopGroupID  uuid.UUID       `json:"cart_shop_group_id"`
	ProductVariantID uuid.UUID       `json:"product_variant_id"`
	Quantity         int16           `json:"quantity"`
	UnitPrice        decimal.Decimal `json:"unit_price"`
	IsSelected       bool            `json:"is_selected"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type CartShopGroup struct {
	ID            uuid.UUID       `json:"id"`
	CartID        uuid.UUID       `json:"cart_id"`
	MerchantOrgID uuid.UUID       `json:"merchant_org_id"`
	IsSelected    bool            `json:"is_selected"`
	Subtotal      decimal.Decimal `json:"subtotal"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Category struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	ParentID       *uuid.UUID `json:"parent_id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Description    *string    `json:"description"`
	SortOrder      int16      `json:"sort_order"`
	IsActive       bool       `json:"is_active"`
	CreatedAt      time.Time  `json:"created_at"`
}

type CheckoutSession struct {
	ID                  uuid.UUID       `json:"id"`
	BuyerCustomerID     uuid.UUID       `json:"buyer_customer_id"`
	BuyerOrgID          uuid.UUID       `json:"buyer_org_id"`
	BuyerMemberID       uuid.UUID       `json:"buyer_member_id"`
	Status              string          `json:"status"`
	IdempotencyKey      *string         `json:"idempotency_key"`
	CheckoutFingerprint string          `json:"checkout_fingerprint"`
	Subtotal            decimal.Decimal `json:"subtotal"`
	TaxTotal            decimal.Decimal `json:"tax_total"`
	ShippingTotal       decimal.Decimal `json:"shipping_total"`
	DiscountTotal       decimal.Decimal `json:"discount_total"`
	GrandTotal          decimal.Decimal `json:"grand_total"`
	Currency            string          `json:"currency"`
	ExpiresAt           *time.Time      `json:"expires_at"`
	CompletedAt         *time.Time      `json:"completed_at"`
	CancelledAt         *time.Time      `json:"cancelled_at"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type Customer struct {
	ID            uuid.UUID `json:"id"`
	IdentityID    uuid.UUID `json:"identity_id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	Image         *string   `json:"image"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CustomerAccount struct {
	ID                    uuid.UUID  `json:"id"`
	CustomerID            uuid.UUID  `json:"customer_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	HashedPassword        *string    `json:"hashed_password"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

type Identity struct {
	ID        uuid.UUID `json:"id"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type Inventory struct {
	ProductVariantID  uuid.UUID `json:"product_variant_id"`
	WarehouseID       int64     `json:"warehouse_id"`
	QuantityOnHand    int32     `json:"quantity_on_hand"`
	QuantityReserved  int32     `json:"quantity_reserved"`
	QuantityAvailable *int32    `json:"quantity_available"`
	LowStockThreshold *int32    `json:"low_stock_threshold"`
	IsActive          bool      `json:"is_active"`
}

type InventoryReservation struct {
	ID                uuid.UUID  `json:"id"`
	CheckoutSessionID uuid.UUID  `json:"checkout_session_id"`
	OrderID           uuid.UUID  `json:"order_id"`
	BuyerOrgID        uuid.UUID  `json:"buyer_org_id"`
	MerchantOrgID     uuid.UUID  `json:"merchant_org_id"`
	Status            string     `json:"status"`
	ExpiresAt         time.Time  `json:"expires_at"`
	ConfirmedAt       *time.Time `json:"confirmed_at"`
	ReleasedAt        *time.Time `json:"released_at"`
	CreatedAt         time.Time  `json:"created_at"`
}

type InventoryReservationItem struct {
	ID               uuid.UUID `json:"id"`
	ReservationID    uuid.UUID `json:"reservation_id"`
	OrderItemID      uuid.UUID `json:"order_item_id"`
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	WarehouseID      int64     `json:"warehouse_id"`
	Quantity         int32     `json:"quantity"`
	CreatedAt        time.Time `json:"created_at"`
}

type Member struct {
	ID             uuid.UUID `json:"id"`
	IdentityID     uuid.UUID `json:"identity_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type MemberRole struct {
	MemberID   uuid.UUID  `json:"member_id"`
	RoleID     int16      `json:"role_id"`
	AssignedBy *uuid.UUID `json:"assigned_by"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Order struct {
	ID                      uuid.UUID       `json:"id"`
	CheckoutSessionID       uuid.UUID       `json:"checkout_session_id"`
	MerchantOrgID           uuid.UUID       `json:"merchant_org_id"`
	BuyerCustomerID         uuid.UUID       `json:"buyer_customer_id"`
	BuyerOrgID              uuid.UUID       `json:"buyer_org_id"`
	BuyerMemberID           uuid.UUID       `json:"buyer_member_id"`
	OrderNumber             string          `json:"order_number"`
	Status                  string          `json:"status"`
	PaymentStatus           string          `json:"payment_status"`
	FulfillmentStatus       string          `json:"fulfillment_status"`
	CustomerEmail           string          `json:"customer_email"`
	CustomerName            string          `json:"customer_name"`
	BillingAddressSnapshot  []byte          `json:"billing_address_snapshot"`
	ShippingAddressSnapshot []byte          `json:"shipping_address_snapshot"`
	Subtotal                decimal.Decimal `json:"subtotal"`
	TaxTotal                decimal.Decimal `json:"tax_total"`
	ShippingTotal           decimal.Decimal `json:"shipping_total"`
	ShippingDiscount        decimal.Decimal `json:"shipping_discount"`
	CouponDiscount          decimal.Decimal `json:"coupon_discount"`
	GrandTotal              decimal.Decimal `json:"grand_total"`
	Currency                string          `json:"currency"`
	PlacedAt                *time.Time      `json:"placed_at"`
	PaidAt                  *time.Time      `json:"paid_at"`
	CancelledAt             *time.Time      `json:"cancelled_at"`
	DeliveredAt             *time.Time      `json:"delivered_at"`
	CompletedAt             *time.Time      `json:"completed_at"`
	CreatedAt               time.Time       `json:"created_at"`
	UpdatedAt               time.Time       `json:"updated_at"`
}

type OrderItem struct {
	ID                uuid.UUID       `json:"id"`
	OrderID           uuid.UUID       `json:"order_id"`
	ProductID         *uuid.UUID      `json:"product_id"`
	ProductVariantID  *uuid.UUID      `json:"product_variant_id"`
	WarehouseID       pgtype.Int8     `json:"warehouse_id"`
	ProductName       string          `json:"product_name"`
	ProductSlug       *string         `json:"product_slug"`
	VariantName       string          `json:"variant_name"`
	Sku               string          `json:"sku"`
	VariantAttributes []byte          `json:"variant_attributes"`
	ThumbnailAssetKey *string         `json:"thumbnail_asset_key"`
	Quantity          int32           `json:"quantity"`
	UnitPrice         decimal.Decimal `json:"unit_price"`
	Subtotal          decimal.Decimal `json:"subtotal"`
	DiscountTotal     decimal.Decimal `json:"discount_total"`
	TaxTotal          decimal.Decimal `json:"tax_total"`
	Total             decimal.Decimal `json:"total"`
	Currency          string          `json:"currency"`
	CreatedAt         time.Time       `json:"created_at"`
}

type OrderStatusHistory struct {
	ID                uuid.UUID  `json:"id"`
	OrderID           uuid.UUID  `json:"order_id"`
	FromStatus        *string    `json:"from_status"`
	ToStatus          string     `json:"to_status"`
	Note              *string    `json:"note"`
	ActorType         string     `json:"actor_type"`
	ChangedByMemberID *uuid.UUID `json:"changed_by_member_id"`
	Metadata          []byte     `json:"metadata"`
	CreatedAt         time.Time  `json:"created_at"`
}

type Organization struct {
	ID         uuid.UUID  `json:"id"`
	ParentID   *uuid.UUID `json:"parent_id"`
	Name       string     `json:"name"`
	Slug       string     `json:"slug"`
	Status     string     `json:"status"`
	Type       string     `json:"type"`
	Capability string     `json:"capability"`
	Logo       *string    `json:"logo"`
	Metadata   []byte     `json:"metadata"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID       `json:"id"`
	CheckoutSessionID uuid.UUID       `json:"checkout_session_id"`
	BuyerOrgID        uuid.UUID       `json:"buyer_org_id"`
	Provider          string          `json:"provider"`
	ProviderPaymentID *string         `json:"provider_payment_id"`
	Status            string          `json:"status"`
	Amount            decimal.Decimal `json:"amount"`
	Currency          string          `json:"currency"`
	Metadata          []byte          `json:"metadata"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type PaymentTransaction struct {
	ID             uuid.UUID       `json:"id"`
	PaymentID      uuid.UUID       `json:"payment_id"`
	Type           string          `json:"type"`
	Status         string          `json:"status"`
	Provider       string          `json:"provider"`
	ProviderRef    *string         `json:"provider_ref"`
	Amount         decimal.Decimal `json:"amount"`
	Currency       string          `json:"currency"`
	FailureCode    *string         `json:"failure_code"`
	FailureMessage *string         `json:"failure_message"`
	Metadata       []byte          `json:"metadata"`
	ProcessedAt    *time.Time      `json:"processed_at"`
	CreatedAt      time.Time       `json:"created_at"`
}

type Product struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	Specification  []byte    `json:"specification"`
	IsFeatured     bool      `json:"is_featured"`
	IdempotencyKey *string   `json:"idempotency_key"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ProductAsset struct {
	ID               int64      `json:"id"`
	ProductID        uuid.UUID  `json:"product_id"`
	ProductVariantID *uuid.UUID `json:"product_variant_id"`
	AssetKey         string     `json:"asset_key"`
	Type             string     `json:"type"`
	MimeType         string     `json:"mime_type"`
	AltText          *string    `json:"alt_text"`
	SortOrder        int16      `json:"sort_order"`
	IsPrimary        bool       `json:"is_primary"`
	DurationSeconds  *int16     `json:"duration_seconds"`
}

type ProductSearchDocument struct {
	ProductID    uuid.UUID   `json:"product_id"`
	SearchVector interface{} `json:"search_vector"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type ProductVariant struct {
	ID             uuid.UUID       `json:"id"`
	ProductID      uuid.UUID       `json:"product_id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	Sku            string          `json:"sku"`
	Name           string          `json:"name"`
	Price          decimal.Decimal `json:"price"`
	TrackInventory bool            `json:"track_inventory"`
	IsActive       bool            `json:"is_active"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type ProductVariantAttribute struct {
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	AttributeValueID int64     `json:"attribute_value_id"`
}

type Role struct {
	ID               int16      `json:"id"`
	RoleName         string     `json:"role_name"`
	OrganizationID   *uuid.UUID `json:"organization_id"`
	OrganizationType string     `json:"organization_type"`
	Slug             string     `json:"slug"`
	IsSystem         bool       `json:"is_system"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type Session struct {
	ID                   uuid.UUID  `json:"id"`
	IdentityID           uuid.UUID  `json:"identity_id"`
	ActiveOrganizationID *uuid.UUID `json:"active_organization_id"`
	Token                string     `json:"token"`
	Service              string     `json:"service"`
	ExpiresAt            time.Time  `json:"expires_at"`
	IpAddress            *string    `json:"ip_address"`
	UserAgent            *string    `json:"user_agent"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	IdentityID    uuid.UUID `json:"identity_id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	Image         *string   `json:"image"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserAccount struct {
	ID                    uuid.UUID  `json:"id"`
	UserID                uuid.UUID  `json:"user_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	HashedPassword        *string    `json:"hashed_password"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

type Warehouse struct {
	ID             int64     `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	AddressID      uuid.UUID `json:"address_id"`
	IsActive       bool      `json:"is_active"`
}
