// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Address struct {
	ID                uuid.UUID `json:"id"`
	OrganizationID    uuid.UUID `json:"organization_id"`
	Type              string    `json:"type"`
	Label             string    `json:"label"`
	Line1             string    `json:"line1"`
	Line2             *string   `json:"line2"`
	PostalCode        string    `json:"postal_code"`
	City              string    `json:"city"`
	State             string    `json:"state"`
	Country           string    `json:"country"`
	IsDefaultShipping bool      `json:"is_default_shipping"`
	IsDefaultBilling  bool      `json:"is_default_billing"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Attribute struct {
	ID             int64      `json:"id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Type           string     `json:"type"`
}

type AttributeValue struct {
	ID             int64      `json:"id"`
	AttributeID    int64      `json:"attribute_id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	Value          string     `json:"value"`
	Label          string     `json:"label"`
	SortOrder      int16      `json:"sort_order"`
}

type Category struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	ParentID       *uuid.UUID `json:"parent_id"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Description    *string    `json:"description"`
	SortOrder      int16      `json:"sort_order"`
	IsActive       bool       `json:"is_active"`
	CreatedAt      time.Time  `json:"created_at"`
}

type Customer struct {
	ID            uuid.UUID `json:"id"`
	IdentityID    uuid.UUID `json:"identity_id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	Image         *string   `json:"image"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CustomerAccount struct {
	ID                    uuid.UUID  `json:"id"`
	CustomerID            uuid.UUID  `json:"customer_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	HashedPassword        *string    `json:"hashed_password"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

type Identity struct {
	ID        uuid.UUID `json:"id"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type Inventory struct {
	ProductVariantID  uuid.UUID `json:"product_variant_id"`
	WarehouseID       int64     `json:"warehouse_id"`
	QuantityOnHand    int32     `json:"quantity_on_hand"`
	QuantityReserved  int32     `json:"quantity_reserved"`
	QuantityAvailable *int32    `json:"quantity_available"`
	LowStockThreshold *int32    `json:"low_stock_threshold"`
	IsActive          bool      `json:"is_active"`
}

type Member struct {
	ID             uuid.UUID `json:"id"`
	IdentityID     uuid.UUID `json:"identity_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type MemberRole struct {
	MemberID   uuid.UUID  `json:"member_id"`
	RoleID     int16      `json:"role_id"`
	AssignedBy *uuid.UUID `json:"assigned_by"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID  `json:"id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	Status    string     `json:"status"`
	Type      string     `json:"type"`
	Logo      *string    `json:"logo"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
}

type Product struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	Specification  []byte    `json:"specification"`
	IsFeatured     bool      `json:"is_featured"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ProductAsset struct {
	ID               int64      `json:"id"`
	ProductID        uuid.UUID  `json:"product_id"`
	ProductVariantID *uuid.UUID `json:"product_variant_id"`
	AssetKey         string     `json:"asset_key"`
	Type             string     `json:"type"`
	MimeType         string     `json:"mime_type"`
	AltText          *string    `json:"alt_text"`
	SortOrder        int16      `json:"sort_order"`
	IsPrimary        bool       `json:"is_primary"`
	DurationSeconds  *int16     `json:"duration_seconds"`
}

type ProductVariant struct {
	ID             uuid.UUID       `json:"id"`
	ProductID      uuid.UUID       `json:"product_id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	Sku            string          `json:"sku"`
	Name           string          `json:"name"`
	Price          decimal.Decimal `json:"price"`
	TrackInventory bool            `json:"track_inventory"`
	IsActive       bool            `json:"is_active"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type ProductVariantAttribute struct {
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	AttributeValueID int64     `json:"attribute_value_id"`
}

type Role struct {
	ID               int16      `json:"id"`
	RoleName         string     `json:"role_name"`
	OrganizationID   *uuid.UUID `json:"organization_id"`
	OrganizationType string     `json:"organization_type"`
	Slug             string     `json:"slug"`
	IsSystem         bool       `json:"is_system"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type Session struct {
	ID         uuid.UUID `json:"id"`
	IdentityID uuid.UUID `json:"identity_id"`
	Token      string    `json:"token"`
	Service    string    `json:"service"`
	ExpiresAt  time.Time `json:"expires_at"`
	IpAddress  *string   `json:"ip_address"`
	UserAgent  *string   `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	IdentityID    uuid.UUID `json:"identity_id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	Image         *string   `json:"image"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserAccount struct {
	ID                    uuid.UUID  `json:"id"`
	UserID                uuid.UUID  `json:"user_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	HashedPassword        *string    `json:"hashed_password"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

type Warehouse struct {
	ID             int64     `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	AddressID      uuid.UUID `json:"address_id"`
	IsActive       bool      `json:"is_active"`
}
