// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_item.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO
    order_items (
        order_id,
        product_id,
        product_variant_id,
        warehouse_id,
        product_name,
        product_slug,
        variant_name,
        sku,
        variant_attributes,
        thumbnail_asset_key,
        quantity,
        unit_price,
        subtotal,
        discount_total,
        tax_total,
        total,
        currency
    )
VALUES
    (
        $1::UUID,
        $2::UUID,
        $3::UUID,
        $4::BIGINT,
        $5::TEXT,
        $6::TEXT,
        $7::TEXT,
        $8::TEXT,
        $9::JSONB,
        $10::TEXT,
        $11::INT,
        $12::NUMERIC,
        $13::NUMERIC,
        $14::NUMERIC,
        $15::NUMERIC,
        $16::NUMERIC,
        $17::TEXT
    )
RETURNING
    id, order_id, product_id, product_variant_id, warehouse_id, product_name, product_slug, variant_name, sku, variant_attributes, thumbnail_asset_key, quantity, unit_price, subtotal, discount_total, tax_total, total, currency, created_at
`

type CreateOrderItemParams struct {
	OrderID           uuid.UUID       `json:"order_id"`
	ProductID         *uuid.UUID      `json:"product_id"`
	ProductVariantID  *uuid.UUID      `json:"product_variant_id"`
	WarehouseID       pgtype.Int8     `json:"warehouse_id"`
	ProductName       string          `json:"product_name"`
	ProductSlug       *string         `json:"product_slug"`
	VariantName       string          `json:"variant_name"`
	Sku               string          `json:"sku"`
	VariantAttributes []byte          `json:"variant_attributes"`
	ThumbnailAssetKey *string         `json:"thumbnail_asset_key"`
	Quantity          int32           `json:"quantity"`
	UnitPrice         decimal.Decimal `json:"unit_price"`
	Subtotal          decimal.Decimal `json:"subtotal"`
	DiscountTotal     decimal.Decimal `json:"discount_total"`
	TaxTotal          decimal.Decimal `json:"tax_total"`
	Total             decimal.Decimal `json:"total"`
	Currency          string          `json:"currency"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductVariantID,
		arg.WarehouseID,
		arg.ProductName,
		arg.ProductSlug,
		arg.VariantName,
		arg.Sku,
		arg.VariantAttributes,
		arg.ThumbnailAssetKey,
		arg.Quantity,
		arg.UnitPrice,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.TaxTotal,
		arg.Total,
		arg.Currency,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.ProductName,
		&i.ProductSlug,
		&i.VariantName,
		&i.Sku,
		&i.VariantAttributes,
		&i.ThumbnailAssetKey,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.Total,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT
    id, order_id, product_id, product_variant_id, warehouse_id, product_name, product_slug, variant_name, sku, variant_attributes, thumbnail_asset_key, quantity, unit_price, subtotal, discount_total, tax_total, total, currency, created_at
FROM
    order_items
WHERE
    id = $1::UUID
LIMIT
    1
`

func (q *Queries) GetOrderItemByID(ctx context.Context, orderItemID uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItemByID, orderItemID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.ProductName,
		&i.ProductSlug,
		&i.VariantName,
		&i.Sku,
		&i.VariantAttributes,
		&i.ThumbnailAssetKey,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.Total,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemWithOrderForReservation = `-- name: GetOrderItemWithOrderForReservation :one
SELECT
    oi.id,
    oi.order_id,
    oi.product_variant_id,
    oi.warehouse_id,
    oi.quantity,
    o.checkout_session_id,
    o.buyer_org_id,
    o.merchant_org_id
FROM
    order_items oi
    JOIN orders o ON o.id = oi.order_id
WHERE
    oi.id = $1::UUID
LIMIT
    1
`

type GetOrderItemWithOrderForReservationRow struct {
	ID                uuid.UUID   `json:"id"`
	OrderID           uuid.UUID   `json:"order_id"`
	ProductVariantID  *uuid.UUID  `json:"product_variant_id"`
	WarehouseID       pgtype.Int8 `json:"warehouse_id"`
	Quantity          int32       `json:"quantity"`
	CheckoutSessionID uuid.UUID   `json:"checkout_session_id"`
	BuyerOrgID        uuid.UUID   `json:"buyer_org_id"`
	MerchantOrgID     uuid.UUID   `json:"merchant_org_id"`
}

func (q *Queries) GetOrderItemWithOrderForReservation(ctx context.Context, orderItemID uuid.UUID) (GetOrderItemWithOrderForReservationRow, error) {
	row := q.db.QueryRow(ctx, getOrderItemWithOrderForReservation, orderItemID)
	var i GetOrderItemWithOrderForReservationRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductVariantID,
		&i.WarehouseID,
		&i.Quantity,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.MerchantOrgID,
	)
	return i, err
}

const listOrderItemsByCheckoutSession = `-- name: ListOrderItemsByCheckoutSession :many
SELECT
    oi.id, oi.order_id, oi.product_id, oi.product_variant_id, oi.warehouse_id, oi.product_name, oi.product_slug, oi.variant_name, oi.sku, oi.variant_attributes, oi.thumbnail_asset_key, oi.quantity, oi.unit_price, oi.subtotal, oi.discount_total, oi.tax_total, oi.total, oi.currency, oi.created_at
FROM
    order_items oi
    JOIN orders o ON o.id = oi.order_id
WHERE
    o.checkout_session_id = $1::UUID
ORDER BY
    o.merchant_org_id,
    oi.created_at,
    oi.id
`

func (q *Queries) ListOrderItemsByCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByCheckoutSession, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.ProductName,
			&i.ProductSlug,
			&i.VariantName,
			&i.Sku,
			&i.VariantAttributes,
			&i.ThumbnailAssetKey,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.TaxTotal,
			&i.Total,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT
    id, order_id, product_id, product_variant_id, warehouse_id, product_name, product_slug, variant_name, sku, variant_attributes, thumbnail_asset_key, quantity, unit_price, subtotal, discount_total, tax_total, total, currency, created_at
FROM
    order_items
WHERE
    order_id = $1::UUID
ORDER BY
    created_at,
    id
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.WarehouseID,
			&i.ProductName,
			&i.ProductSlug,
			&i.VariantName,
			&i.Sku,
			&i.VariantAttributes,
			&i.ThumbnailAssetKey,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.TaxTotal,
			&i.Total,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
