// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_status_history.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrderStatusHistory = `-- name: CreateOrderStatusHistory :one
INSERT INTO
    order_status_histories (
        order_id,
        from_status,
        to_status,
        note,
        actor_type,
        changed_by_member_id,
        metadata
    )
VALUES
    (
        $1::UUID,
        $2::TEXT,
        $3::TEXT,
        $4::TEXT,
        $5::TEXT,
        $6::UUID,
        $7::JSONB
    )
RETURNING
    id, order_id, from_status, to_status, note, actor_type, changed_by_member_id, metadata, created_at
`

type CreateOrderStatusHistoryParams struct {
	OrderID           uuid.UUID  `json:"order_id"`
	FromStatus        *string    `json:"from_status"`
	ToStatus          string     `json:"to_status"`
	Note              *string    `json:"note"`
	ActorType         string     `json:"actor_type"`
	ChangedByMemberID *uuid.UUID `json:"changed_by_member_id"`
	Metadata          []byte     `json:"metadata"`
}

func (q *Queries) CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRow(ctx, createOrderStatusHistory,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Note,
		arg.ActorType,
		arg.ChangedByMemberID,
		arg.Metadata,
	)
	var i OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Note,
		&i.ActorType,
		&i.ChangedByMemberID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderStatusHistory = `-- name: ListOrderStatusHistory :many
SELECT
    id, order_id, from_status, to_status, note, actor_type, changed_by_member_id, metadata, created_at
FROM
    order_status_histories
WHERE
    order_id = $1::UUID
ORDER BY
    created_at DESC,
    id DESC
`

func (q *Queries) ListOrderStatusHistory(ctx context.Context, orderID uuid.UUID) ([]OrderStatusHistory, error) {
	rows, err := q.db.Query(ctx, listOrderStatusHistory, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderStatusHistory{}
	for rows.Next() {
		var i OrderStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Note,
			&i.ActorType,
			&i.ChangedByMemberID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
