// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE
    orders
SET
    "status" = 'cancelled',
    cancelled_at = COALESCE(cancelled_at, NOW()),
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" IN ('pending_payment', 'placed', 'processing')
RETURNING
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
`

func (q *Queries) CancelOrder(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, orderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO
    orders (
        checkout_session_id,
        merchant_org_id,
        buyer_customer_id,
        buyer_org_id,
        buyer_member_id,
        order_number,
        "status",
        payment_status,
        fulfillment_status,
        customer_email,
        customer_name,
        billing_address_snapshot,
        shipping_address_snapshot,
        subtotal,
        tax_total,
        shipping_total,
        shipping_discount,
        coupon_discount,
        grand_total,
        currency
    )
VALUES
    (
        $1::UUID,
        $2::UUID,
        $3::UUID,
        $4::UUID,
        $5::UUID,
        $6::TEXT,
        COALESCE($7::TEXT, 'pending_payment'),
        COALESCE($8::TEXT, 'unpaid'),
        COALESCE($9::TEXT, 'unfulfilled'),
        $10::TEXT,
        $11::TEXT,
        $12::JSONB,
        $13::JSONB,
        $14::NUMERIC,
        $15::NUMERIC,
        $16::NUMERIC,
        $17::NUMERIC,
        $18::NUMERIC,
        $19::NUMERIC,
        $20::TEXT
    )
RETURNING
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
`

type CreateOrderParams struct {
	CheckoutSessionID       uuid.UUID       `json:"checkout_session_id"`
	MerchantOrgID           uuid.UUID       `json:"merchant_org_id"`
	BuyerCustomerID         uuid.UUID       `json:"buyer_customer_id"`
	BuyerOrgID              uuid.UUID       `json:"buyer_org_id"`
	BuyerMemberID           uuid.UUID       `json:"buyer_member_id"`
	OrderNumber             string          `json:"order_number"`
	Status                  *string         `json:"status"`
	PaymentStatus           *string         `json:"payment_status"`
	FulfillmentStatus       *string         `json:"fulfillment_status"`
	CustomerEmail           string          `json:"customer_email"`
	CustomerName            string          `json:"customer_name"`
	BillingAddressSnapshot  []byte          `json:"billing_address_snapshot"`
	ShippingAddressSnapshot []byte          `json:"shipping_address_snapshot"`
	Subtotal                decimal.Decimal `json:"subtotal"`
	TaxTotal                decimal.Decimal `json:"tax_total"`
	ShippingTotal           decimal.Decimal `json:"shipping_total"`
	ShippingDiscount        decimal.Decimal `json:"shipping_discount"`
	CouponDiscount          decimal.Decimal `json:"coupon_discount"`
	GrandTotal              decimal.Decimal `json:"grand_total"`
	Currency                string          `json:"currency"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CheckoutSessionID,
		arg.MerchantOrgID,
		arg.BuyerCustomerID,
		arg.BuyerOrgID,
		arg.BuyerMemberID,
		arg.OrderNumber,
		arg.Status,
		arg.PaymentStatus,
		arg.FulfillmentStatus,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.BillingAddressSnapshot,
		arg.ShippingAddressSnapshot,
		arg.Subtotal,
		arg.TaxTotal,
		arg.ShippingTotal,
		arg.ShippingDiscount,
		arg.CouponDiscount,
		arg.GrandTotal,
		arg.Currency,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePendingOrder = `-- name: ExpirePendingOrder :one
UPDATE
    orders
SET
    "status" = 'expired',
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" = 'pending_payment'
RETURNING
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
`

func (q *Queries) ExpirePendingOrder(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, expirePendingOrder, orderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
FROM
    orders
WHERE
    id = $1::UUID
LIMIT
    1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForBuyer = `-- name: GetOrderForBuyer :one
SELECT
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
FROM
    orders
WHERE
    id = $1::UUID
    AND buyer_org_id = $2::UUID
LIMIT
    1
`

type GetOrderForBuyerParams struct {
	OrderID    uuid.UUID `json:"order_id"`
	BuyerOrgID uuid.UUID `json:"buyer_org_id"`
}

func (q *Queries) GetOrderForBuyer(ctx context.Context, arg GetOrderForBuyerParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForBuyer, arg.OrderID, arg.BuyerOrgID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForMerchant = `-- name: GetOrderForMerchant :one
SELECT
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
FROM
    orders
WHERE
    id = $1::UUID
    AND merchant_org_id = $2::UUID
LIMIT
    1
`

type GetOrderForMerchantParams struct {
	OrderID       uuid.UUID `json:"order_id"`
	MerchantOrgID uuid.UUID `json:"merchant_org_id"`
}

func (q *Queries) GetOrderForMerchant(ctx context.Context, arg GetOrderForMerchantParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForMerchant, arg.OrderID, arg.MerchantOrgID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
FROM
    orders
WHERE
    id = $1::UUID
FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, orderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBuyerOrders = `-- name: ListBuyerOrders :many
SELECT
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
FROM
    orders
WHERE
    buyer_org_id = $1::UUID
    AND (
        NOT $2::BOOL
        OR (created_at, id) < ($3::TIMESTAMPTZ, $4::UUID)
    )
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    $5::INT
`

type ListBuyerOrdersParams struct {
	BuyerOrgID     uuid.UUID `json:"buyer_org_id"`
	HasCursor      bool      `json:"has_cursor"`
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterID        uuid.UUID `json:"after_id"`
	PageLimit      int32     `json:"page_limit"`
}

func (q *Queries) ListBuyerOrders(ctx context.Context, arg ListBuyerOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listBuyerOrders,
		arg.BuyerOrgID,
		arg.HasCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.MerchantOrgID,
			&i.BuyerCustomerID,
			&i.BuyerOrgID,
			&i.BuyerMemberID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.FulfillmentStatus,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.BillingAddressSnapshot,
			&i.ShippingAddressSnapshot,
			&i.Subtotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.ShippingDiscount,
			&i.CouponDiscount,
			&i.GrandTotal,
			&i.Currency,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantOrders = `-- name: ListMerchantOrders :many
SELECT
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
FROM
    orders
WHERE
    merchant_org_id = $1::UUID
    AND (
        NOT $2::BOOL
        OR "status" = $3::TEXT
    )
    AND (
        NOT $4::BOOL
        OR (created_at, id) < ($5::TIMESTAMPTZ, $6::UUID)
    )
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    $7::INT
`

type ListMerchantOrdersParams struct {
	MerchantOrgID  uuid.UUID `json:"merchant_org_id"`
	HasStatus      bool      `json:"has_status"`
	Status         string    `json:"status"`
	HasCursor      bool      `json:"has_cursor"`
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterID        uuid.UUID `json:"after_id"`
	PageLimit      int32     `json:"page_limit"`
}

func (q *Queries) ListMerchantOrders(ctx context.Context, arg ListMerchantOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listMerchantOrders,
		arg.MerchantOrgID,
		arg.HasStatus,
		arg.Status,
		arg.HasCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.MerchantOrgID,
			&i.BuyerCustomerID,
			&i.BuyerOrgID,
			&i.BuyerMemberID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.FulfillmentStatus,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.BillingAddressSnapshot,
			&i.ShippingAddressSnapshot,
			&i.Subtotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.ShippingDiscount,
			&i.CouponDiscount,
			&i.GrandTotal,
			&i.Currency,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCheckoutSession = `-- name: ListOrdersByCheckoutSession :many
SELECT
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
FROM
    orders
WHERE
    checkout_session_id = $1::UUID
ORDER BY
    merchant_org_id,
    id
`

func (q *Queries) ListOrdersByCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCheckoutSession, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.MerchantOrgID,
			&i.BuyerCustomerID,
			&i.BuyerOrgID,
			&i.BuyerMemberID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.FulfillmentStatus,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.BillingAddressSnapshot,
			&i.ShippingAddressSnapshot,
			&i.Subtotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.ShippingDiscount,
			&i.CouponDiscount,
			&i.GrandTotal,
			&i.Currency,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaymentFailed = `-- name: MarkOrderPaymentFailed :one
UPDATE
    orders
SET
    payment_status = 'failed',
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND payment_status IN ('unpaid', 'authorized')
RETURNING
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
`

func (q *Queries) MarkOrderPaymentFailed(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaymentFailed, orderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderPlacedPaid = `-- name: MarkOrderPlacedPaid :one
UPDATE
    orders
SET
    "status" = 'placed',
    payment_status = 'paid',
    placed_at = COALESCE(placed_at, NOW()),
    paid_at = COALESCE(paid_at, NOW()),
    updated_at = NOW()
WHERE
    id = $1::UUID
    AND "status" = 'pending_payment'
RETURNING
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
`

func (q *Queries) MarkOrderPlacedPaid(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPlacedPaid, orderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrdersPlacedPaidByCheckoutSession = `-- name: MarkOrdersPlacedPaidByCheckoutSession :many
UPDATE
    orders
SET
    "status" = 'placed',
    payment_status = 'paid',
    placed_at = COALESCE(placed_at, NOW()),
    paid_at = COALESCE(paid_at, NOW()),
    updated_at = NOW()
WHERE
    checkout_session_id = $1::UUID
    AND "status" = 'pending_payment'
RETURNING
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
`

func (q *Queries) MarkOrdersPlacedPaidByCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, markOrdersPlacedPaidByCheckoutSession, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.MerchantOrgID,
			&i.BuyerCustomerID,
			&i.BuyerOrgID,
			&i.BuyerMemberID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.FulfillmentStatus,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.BillingAddressSnapshot,
			&i.ShippingAddressSnapshot,
			&i.Subtotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.ShippingDiscount,
			&i.CouponDiscount,
			&i.GrandTotal,
			&i.Currency,
			&i.PlacedAt,
			&i.PaidAt,
			&i.CancelledAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderFulfillmentStatus = `-- name: UpdateOrderFulfillmentStatus :one
UPDATE
    orders
SET
    fulfillment_status = $1::TEXT,
    delivered_at = CASE
        WHEN $1::TEXT = 'delivered' THEN COALESCE(delivered_at, NOW())
        ELSE delivered_at
    END,
    completed_at = CASE
        WHEN $1::TEXT = 'delivered' THEN COALESCE(completed_at, NOW())
        ELSE completed_at
    END,
    updated_at = NOW()
WHERE
    id = $2::UUID
RETURNING
    id, checkout_session_id, merchant_org_id, buyer_customer_id, buyer_org_id, buyer_member_id, order_number, status, payment_status, fulfillment_status, customer_email, customer_name, billing_address_snapshot, shipping_address_snapshot, subtotal, tax_total, shipping_total, shipping_discount, coupon_discount, grand_total, currency, placed_at, paid_at, cancelled_at, delivered_at, completed_at, created_at, updated_at
`

type UpdateOrderFulfillmentStatusParams struct {
	FulfillmentStatus string    `json:"fulfillment_status"`
	OrderID           uuid.UUID `json:"order_id"`
}

func (q *Queries) UpdateOrderFulfillmentStatus(ctx context.Context, arg UpdateOrderFulfillmentStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderFulfillmentStatus, arg.FulfillmentStatus, arg.OrderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.MerchantOrgID,
		&i.BuyerCustomerID,
		&i.BuyerOrgID,
		&i.BuyerMemberID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.BillingAddressSnapshot,
		&i.ShippingAddressSnapshot,
		&i.Subtotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.ShippingDiscount,
		&i.CouponDiscount,
		&i.GrandTotal,
		&i.Currency,
		&i.PlacedAt,
		&i.PaidAt,
		&i.CancelledAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
