// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    parent_id
    , name
    , slug
    , status
    , type
    , metadata
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, parent_id, name, slug, status, type, logo, metadata, created_at
`

type CreateOrganizationParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
	Slug     string     `json:"slug"`
	Status   string     `json:"status"`
	Type     string     `json:"type"`
	Metadata []byte     `json:"metadata"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.Type,
		arg.Metadata,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Type,
		&i.Logo,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT
    id
    , parent_id
    , name
    , slug
    , status
    , type
    , logo
    , metadata
    , created_at
FROM organizations
WHERE id = $1
ORDER BY id
LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Type,
		&i.Logo,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
