// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO
    payments (
        checkout_session_id,
        buyer_org_id,
        provider,
        provider_payment_id,
        "status",
        amount,
        currency,
        metadata
    )
VALUES
    (
        $1::UUID,
        $2::UUID,
        $3::TEXT,
        $4::TEXT,
        COALESCE($5::TEXT, 'pending'),
        $6::NUMERIC,
        $7::TEXT,
        $8::JSONB
    )
RETURNING
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
`

type CreatePaymentParams struct {
	CheckoutSessionID uuid.UUID       `json:"checkout_session_id"`
	BuyerOrgID        uuid.UUID       `json:"buyer_org_id"`
	Provider          string          `json:"provider"`
	ProviderPaymentID *string         `json:"provider_payment_id"`
	Status            *string         `json:"status"`
	Amount            decimal.Decimal `json:"amount"`
	Currency          string          `json:"currency"`
	Metadata          []byte          `json:"metadata"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.CheckoutSessionID,
		arg.BuyerOrgID,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.Metadata,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO
    payment_transactions (
        payment_id,
        "type",
        "status",
        provider,
        provider_ref,
        amount,
        currency,
        failure_code,
        failure_message,
        metadata,
        processed_at
    )
VALUES
    (
        $1::UUID,
        $2::TEXT,
        $3::TEXT,
        $4::TEXT,
        $5::TEXT,
        $6::NUMERIC,
        $7::TEXT,
        $8::TEXT,
        $9::TEXT,
        $10::JSONB,
        $11::TIMESTAMPTZ
    )
RETURNING
    id, payment_id, type, status, provider, provider_ref, amount, currency, failure_code, failure_message, metadata, processed_at, created_at
`

type CreatePaymentTransactionParams struct {
	PaymentID      uuid.UUID       `json:"payment_id"`
	Type           string          `json:"type"`
	Status         string          `json:"status"`
	Provider       string          `json:"provider"`
	ProviderRef    *string         `json:"provider_ref"`
	Amount         decimal.Decimal `json:"amount"`
	Currency       string          `json:"currency"`
	FailureCode    *string         `json:"failure_code"`
	FailureMessage *string         `json:"failure_message"`
	Metadata       []byte          `json:"metadata"`
	ProcessedAt    *time.Time      `json:"processed_at"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction,
		arg.PaymentID,
		arg.Type,
		arg.Status,
		arg.Provider,
		arg.ProviderRef,
		arg.Amount,
		arg.Currency,
		arg.FailureCode,
		arg.FailureMessage,
		arg.Metadata,
		arg.ProcessedAt,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Type,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.Amount,
		&i.Currency,
		&i.FailureCode,
		&i.FailureMessage,
		&i.Metadata,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
FROM
    payments
WHERE
    id = $1::UUID
LIMIT
    1
`

func (q *Queries) GetPaymentByID(ctx context.Context, paymentID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, paymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderPaymentID = `-- name: GetPaymentByProviderPaymentID :one
SELECT
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
FROM
    payments
WHERE
    provider = $1::TEXT
    AND provider_payment_id = $2::TEXT
LIMIT
    1
`

type GetPaymentByProviderPaymentIDParams struct {
	Provider          string `json:"provider"`
	ProviderPaymentID string `json:"provider_payment_id"`
}

func (q *Queries) GetPaymentByProviderPaymentID(ctx context.Context, arg GetPaymentByProviderPaymentIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderPaymentID, arg.Provider, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
FROM
    payments
WHERE
    id = $1::UUID
FOR UPDATE
`

func (q *Queries) GetPaymentForUpdate(ctx context.Context, paymentID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, paymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTransactionByProviderRef = `-- name: GetPaymentTransactionByProviderRef :one
SELECT
    id, payment_id, type, status, provider, provider_ref, amount, currency, failure_code, failure_message, metadata, processed_at, created_at
FROM
    payment_transactions
WHERE
    provider = $1::TEXT
    AND provider_ref = $2::TEXT
LIMIT
    1
`

type GetPaymentTransactionByProviderRefParams struct {
	Provider    string `json:"provider"`
	ProviderRef string `json:"provider_ref"`
}

func (q *Queries) GetPaymentTransactionByProviderRef(ctx context.Context, arg GetPaymentTransactionByProviderRefParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getPaymentTransactionByProviderRef, arg.Provider, arg.ProviderRef)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Type,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.Amount,
		&i.Currency,
		&i.FailureCode,
		&i.FailureMessage,
		&i.Metadata,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentTransactionsByPayment = `-- name: ListPaymentTransactionsByPayment :many
SELECT
    id, payment_id, type, status, provider, provider_ref, amount, currency, failure_code, failure_message, metadata, processed_at, created_at
FROM
    payment_transactions
WHERE
    payment_id = $1::UUID
ORDER BY
    created_at,
    id
`

func (q *Queries) ListPaymentTransactionsByPayment(ctx context.Context, paymentID uuid.UUID) ([]PaymentTransaction, error) {
	rows, err := q.db.Query(ctx, listPaymentTransactionsByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentTransaction{}
	for rows.Next() {
		var i PaymentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.Type,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.Amount,
			&i.Currency,
			&i.FailureCode,
			&i.FailureMessage,
			&i.Metadata,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByCheckoutSession = `-- name: ListPaymentsByCheckoutSession :many
SELECT
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
FROM
    payments
WHERE
    checkout_session_id = $1::UUID
ORDER BY
    created_at,
    id
`

func (q *Queries) ListPaymentsByCheckoutSession(ctx context.Context, checkoutSessionID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByCheckoutSession, checkoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutSessionID,
			&i.BuyerOrgID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE
    payments
SET
    "status" = 'failed',
    metadata = COALESCE($1::JSONB, metadata),
    updated_at = NOW()
WHERE
    id = $2::UUID
    AND "status" IN ('pending', 'requires_action', 'authorized')
RETURNING
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
`

type MarkPaymentFailedParams struct {
	Metadata  []byte    `json:"metadata"`
	PaymentID uuid.UUID `json:"payment_id"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.Metadata, arg.PaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :one
UPDATE
    payments
SET
    "status" = 'succeeded',
    metadata = COALESCE($1::JSONB, metadata),
    updated_at = NOW()
WHERE
    id = $2::UUID
    AND "status" IN ('pending', 'requires_action', 'authorized')
RETURNING
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
`

type MarkPaymentSucceededParams struct {
	Metadata  []byte    `json:"metadata"`
	PaymentID uuid.UUID `json:"payment_id"`
}

func (q *Queries) MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentSucceeded, arg.Metadata, arg.PaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentProviderPaymentID = `-- name: UpdatePaymentProviderPaymentID :one
UPDATE
    payments
SET
    provider_payment_id = $1::TEXT,
    updated_at = NOW()
WHERE
    id = $2::UUID
RETURNING
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
`

type UpdatePaymentProviderPaymentIDParams struct {
	ProviderPaymentID string    `json:"provider_payment_id"`
	PaymentID         uuid.UUID `json:"payment_id"`
}

func (q *Queries) UpdatePaymentProviderPaymentID(ctx context.Context, arg UpdatePaymentProviderPaymentIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentProviderPaymentID, arg.ProviderPaymentID, arg.PaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE
    payments
SET
    "status" = $1::TEXT,
    metadata = COALESCE($2::JSONB, metadata),
    updated_at = NOW()
WHERE
    id = $3::UUID
RETURNING
    id, checkout_session_id, buyer_org_id, provider, provider_payment_id, status, amount, currency, metadata, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	Status    string    `json:"status"`
	Metadata  []byte    `json:"metadata"`
	PaymentID uuid.UUID `json:"payment_id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.Status, arg.Metadata, arg.PaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutSessionID,
		&i.BuyerOrgID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
