// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_variant.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO
    product_variants (
        product_id,
        organization_id,
        sku,
        name,
        price
    )
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, product_id, organization_id, sku, name, price, track_inventory, is_active, created_at, updated_at
`

type CreateProductVariantParams struct {
	ProductID      uuid.UUID       `json:"product_id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	Sku            string          `json:"sku"`
	Name           string          `json:"name"`
	Price          decimal.Decimal `json:"price"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.OrganizationID,
		arg.Sku,
		arg.Name,
		arg.Price,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrganizationID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.TrackInventory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
UPDATE
    product_variants
SET
    is_active = FALSE,
    updated_at = NOW()
WHERE
    id = $1
    AND organization_id = $2
`

type DeleteProductVariantParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteProductVariant(ctx context.Context, arg DeleteProductVariantParams) error {
	_, err := q.db.Exec(ctx, deleteProductVariant, arg.ID, arg.OrganizationID)
	return err
}

const getActiveVariantForCart = `-- name: GetActiveVariantForCart :one
SELECT
    v.id,
    v.organization_id AS merchant_org_id,
    v.price,
    v.name AS variant_name,
    v.sku,
    v.is_active AS variant_is_active,
    p.id AS product_id,
    p.name AS product_name,
    p.slug AS product_slug,
    p.status AS product_status
FROM
    product_variants v
    JOIN products p ON p.id = v.product_id
WHERE
    v.id = $1
    AND v.is_active = TRUE
    AND p.status = 'active'
`

type GetActiveVariantForCartRow struct {
	ID              uuid.UUID       `json:"id"`
	MerchantOrgID   uuid.UUID       `json:"merchant_org_id"`
	Price           decimal.Decimal `json:"price"`
	VariantName     string          `json:"variant_name"`
	Sku             string          `json:"sku"`
	VariantIsActive bool            `json:"variant_is_active"`
	ProductID       uuid.UUID       `json:"product_id"`
	ProductName     string          `json:"product_name"`
	ProductSlug     string          `json:"product_slug"`
	ProductStatus   string          `json:"product_status"`
}

func (q *Queries) GetActiveVariantForCart(ctx context.Context, id uuid.UUID) (GetActiveVariantForCartRow, error) {
	row := q.db.QueryRow(ctx, getActiveVariantForCart, id)
	var i GetActiveVariantForCartRow
	err := row.Scan(
		&i.ID,
		&i.MerchantOrgID,
		&i.Price,
		&i.VariantName,
		&i.Sku,
		&i.VariantIsActive,
		&i.ProductID,
		&i.ProductName,
		&i.ProductSlug,
		&i.ProductStatus,
	)
	return i, err
}

const getProductVariantByID = `-- name: GetProductVariantByID :one
SELECT
    id,
    product_id,
    organization_id,
    sku,
    name,
    price,
    track_inventory,
    is_active,
    created_at,
    updated_at
FROM
    product_variants
WHERE
    id = $1
ORDER BY
    id
LIMIT
    1
`

func (q *Queries) GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getProductVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrganizationID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.TrackInventory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductVariantsByProductID = `-- name: ListProductVariantsByProductID :many
SELECT
    id,
    product_id,
    organization_id,
    sku,
    name,
    price,
    track_inventory,
    is_active,
    created_at,
    updated_at
FROM
    product_variants
WHERE
    product_id = $1
ORDER BY
    id
`

func (q *Queries) ListProductVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProductVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OrganizationID,
			&i.Sku,
			&i.Name,
			&i.Price,
			&i.TrackInventory,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsByProductIDs = `-- name: ListProductVariantsByProductIDs :many
SELECT
    id,
    product_id,
    organization_id,
    sku,
    name,
    price,
    track_inventory,
    is_active,
    created_at,
    updated_at
FROM
    product_variants
WHERE
    product_id = ANY ($1::UUID [])
ORDER BY
    product_id,
    id
`

func (q *Queries) ListProductVariantsByProductIDs(ctx context.Context, productIds []uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProductVariantsByProductIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OrganizationID,
			&i.Sku,
			&i.Name,
			&i.Price,
			&i.TrackInventory,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE
    product_variants
SET
    name = $3,
    price = $4,
    updated_at = NOW()
WHERE
    id = $1
    AND organization_id = $2
RETURNING
    id, product_id, organization_id, sku, name, price, track_inventory, is_active, created_at, updated_at
`

type UpdateProductVariantParams struct {
	ID             uuid.UUID       `json:"id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	Name           string          `json:"name"`
	Price          decimal.Decimal `json:"price"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProductVariant,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Price,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrganizationID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.TrackInventory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
