// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variant_attribute.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignAttributeValueToProductVariant = `-- name: AssignAttributeValueToProductVariant :exec
INSERT INTO product_variant_attributes (
    product_variant_id
    , attribute_value_id
) VALUES ($1, $2)
`

type AssignAttributeValueToProductVariantParams struct {
	ProductVariantID uuid.UUID `json:"product_variant_id"`
	AttributeValueID int64     `json:"attribute_value_id"`
}

func (q *Queries) AssignAttributeValueToProductVariant(ctx context.Context, arg AssignAttributeValueToProductVariantParams) error {
	_, err := q.db.Exec(ctx, assignAttributeValueToProductVariant, arg.ProductVariantID, arg.AttributeValueID)
	return err
}
