// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_asset.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProductAsset = `-- name: CreateProductAsset :one
INSERT INTO
    product_assets (
        product_id,
        product_variant_id,
        asset_key,
        "type",
        mime_type,
        alt_text,
        sort_order,
        is_primary,
        duration_seconds
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id, product_id, product_variant_id, asset_key, type, mime_type, alt_text, sort_order, is_primary, duration_seconds
`

type CreateProductAssetParams struct {
	ProductID        uuid.UUID  `json:"product_id"`
	ProductVariantID *uuid.UUID `json:"product_variant_id"`
	AssetKey         string     `json:"asset_key"`
	Type             string     `json:"type"`
	MimeType         string     `json:"mime_type"`
	AltText          *string    `json:"alt_text"`
	SortOrder        int16      `json:"sort_order"`
	IsPrimary        bool       `json:"is_primary"`
	DurationSeconds  *int16     `json:"duration_seconds"`
}

func (q *Queries) CreateProductAsset(ctx context.Context, arg CreateProductAssetParams) (ProductAsset, error) {
	row := q.db.QueryRow(ctx, createProductAsset,
		arg.ProductID,
		arg.ProductVariantID,
		arg.AssetKey,
		arg.Type,
		arg.MimeType,
		arg.AltText,
		arg.SortOrder,
		arg.IsPrimary,
		arg.DurationSeconds,
	)
	var i ProductAsset
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductVariantID,
		&i.AssetKey,
		&i.Type,
		&i.MimeType,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.DurationSeconds,
	)
	return i, err
}

const deleteProductAssetsByProductID = `-- name: DeleteProductAssetsByProductID :exec
DELETE FROM
    product_assets
WHERE
    product_id = $1
`

func (q *Queries) DeleteProductAssetsByProductID(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductAssetsByProductID, productID)
	return err
}

const listProductAssetsByProductID = `-- name: ListProductAssetsByProductID :many
SELECT
    id,
    product_id,
    product_variant_id,
    asset_key,
    "type",
    mime_type,
    alt_text,
    sort_order,
    is_primary,
    duration_seconds
FROM
    product_assets
WHERE
    product_id = $1
ORDER BY
    sort_order
`

func (q *Queries) ListProductAssetsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductAsset, error) {
	rows, err := q.db.Query(ctx, listProductAssetsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductAsset{}
	for rows.Next() {
		var i ProductAsset
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.AssetKey,
			&i.Type,
			&i.MimeType,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAssetsByProductIDs = `-- name: ListProductAssetsByProductIDs :many
SELECT
    id,
    product_id,
    product_variant_id,
    asset_key,
    "type",
    mime_type,
    alt_text,
    sort_order,
    is_primary,
    duration_seconds
FROM
    product_assets
WHERE
    product_id = ANY ($1::UUID [])
ORDER BY
    product_id,
    sort_order
`

func (q *Queries) ListProductAssetsByProductIDs(ctx context.Context, productIds []uuid.UUID) ([]ProductAsset, error) {
	rows, err := q.db.Query(ctx, listProductAssetsByProductIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductAsset{}
	for rows.Next() {
		var i ProductAsset
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductVariantID,
			&i.AssetKey,
			&i.Type,
			&i.MimeType,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
