// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variant.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (
    product_id
    , organization_id
    , sku
    , name
    , price
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, organization_id, sku, name, price, track_inventory, is_active, created_at, updated_at
`

type CreateProductVariantParams struct {
	ProductID      uuid.UUID       `json:"product_id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	Sku            string          `json:"sku"`
	Name           string          `json:"name"`
	Price          decimal.Decimal `json:"price"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.OrganizationID,
		arg.Sku,
		arg.Name,
		arg.Price,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrganizationID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.TrackInventory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductVariantByID = `-- name: GetProductVariantByID :one
SELECT
    id
    , product_id
    , organization_id
    , sku
    , name
    , price
    , track_inventory
    , is_active
    , created_at
    , updated_at
FROM product_variants
WHERE id = $1
ORDER BY id
LIMIT 1
`

func (q *Queries) GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getProductVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrganizationID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.TrackInventory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
