// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
    products (
        organization_id,
        category_id,
        name,
        slug,
        description,
        specification,
        idempotency_key
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, organization_id, category_id, name, slug, description, status, specification, is_featured, idempotency_key, created_at, updated_at
`

type CreateProductParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Specification  []byte    `json:"specification"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrganizationID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Specification,
		arg.IdempotencyKey,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Specification,
		&i.IsFeatured,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM
    products
WHERE
    id = $1
    AND organization_id = $2
`

type DeleteProductParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.OrganizationID)
	return err
}

const getActiveProductByID = `-- name: GetActiveProductByID :one
SELECT
    id,
    organization_id,
    category_id,
    name,
    slug,
    description,
    "status",
    is_featured,
    specification,
    created_at,
    updated_at
FROM
    products
WHERE
    id = $1
    AND "status" = 'active'
LIMIT
    1
`

type GetActiveProductByIDRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetActiveProductByID(ctx context.Context, id uuid.UUID) (GetActiveProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveProductByID, id)
	var i GetActiveProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.IsFeatured,
		&i.Specification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProductBySlug = `-- name: GetActiveProductBySlug :one
SELECT
    id,
    organization_id,
    category_id,
    name,
    slug,
    description,
    "status",
    is_featured,
    specification,
    created_at,
    updated_at
FROM
    products
WHERE
    organization_id = $1
    AND slug = $2
    AND "status" = 'active'
LIMIT
    1
`

type GetActiveProductBySlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetActiveProductBySlugRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetActiveProductBySlug(ctx context.Context, arg GetActiveProductBySlugParams) (GetActiveProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getActiveProductBySlug, arg.OrganizationID, arg.Slug)
	var i GetActiveProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.IsFeatured,
		&i.Specification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id,
    organization_id,
    category_id,
    name,
    slug,
    description,
    "status",
    is_featured,
    specification,
    created_at,
    updated_at
FROM
    products
WHERE
    id = $1
ORDER BY
    id
LIMIT
    1
`

type GetProductByIDRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.IsFeatured,
		&i.Specification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByIdempotencyKey = `-- name: GetProductByIdempotencyKey :one
SELECT
    id, organization_id, category_id, name, slug, description, status, specification, is_featured, idempotency_key, created_at, updated_at
FROM
    products
WHERE
    organization_id = $1
    AND idempotency_key = $2
`

type GetProductByIdempotencyKeyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetProductByIdempotencyKey(ctx context.Context, arg GetProductByIdempotencyKeyParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByIdempotencyKey, arg.OrganizationID, arg.IdempotencyKey)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Specification,
		&i.IsFeatured,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT
    id,
    organization_id,
    category_id,
    name,
    slug,
    description,
    "status",
    is_featured,
    specification,
    created_at,
    updated_at
FROM
    products
WHERE
    organization_id = $1
    AND slug = $2
LIMIT
    1
`

type GetProductBySlugParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
}

type GetProductBySlugRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, arg.OrganizationID, arg.Slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.IsFeatured,
		&i.Specification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProductsAfter = `-- name: ListActiveProductsAfter :many
SELECT
    id,
    organization_id,
    category_id,
    name,
    slug,
    description,
    "status",
    is_featured,
    specification,
    created_at,
    updated_at
FROM
    products
WHERE
    "status" = 'active'
    AND (created_at, id) < (
        $1::TIMESTAMPTZ,
        $2::UUID
    )
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    $3::INT
`

type ListActiveProductsAfterParams struct {
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterID        uuid.UUID `json:"after_id"`
	PageLimit      int32     `json:"page_limit"`
}

type ListActiveProductsAfterRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListActiveProductsAfter(ctx context.Context, arg ListActiveProductsAfterParams) ([]ListActiveProductsAfterRow, error) {
	rows, err := q.db.Query(ctx, listActiveProductsAfter, arg.AfterCreatedAt, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsAfterRow{}
	for rows.Next() {
		var i ListActiveProductsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.IsFeatured,
			&i.Specification,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByOrganization = `-- name: ListProductsByOrganization :many
SELECT
    id,
    organization_id,
    category_id,
    name,
    slug,
    description,
    "status",
    is_featured,
    specification,
    created_at,
    updated_at
FROM
    products
WHERE
    organization_id = $1
ORDER BY
    created_at DESC
`

type ListProductsByOrganizationRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListProductsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListProductsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listProductsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByOrganizationRow{}
	for rows.Next() {
		var i ListProductsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.IsFeatured,
			&i.Specification,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByOrganizationWithStatus = `-- name: ListProductsByOrganizationWithStatus :many
SELECT
    id,
    organization_id,
    category_id,
    name,
    slug,
    description,
    "status",
    is_featured,
    specification,
    created_at,
    updated_at
FROM
    products
WHERE
    organization_id = $1
    AND "status" = ANY($2::TEXT [])
    AND (created_at, id) < (
        $3::TIMESTAMPTZ,
        $4::UUID
    )
ORDER BY
    created_at DESC,
    id DESC
LIMIT
    $5::INT
`

type ListProductsByOrganizationWithStatusParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Statuses       []string  `json:"statuses"`
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterID        uuid.UUID `json:"after_id"`
	PageLimit      int32     `json:"page_limit"`
}

type ListProductsByOrganizationWithStatusRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListProductsByOrganizationWithStatus(ctx context.Context, arg ListProductsByOrganizationWithStatusParams) ([]ListProductsByOrganizationWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listProductsByOrganizationWithStatus,
		arg.OrganizationID,
		arg.Statuses,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByOrganizationWithStatusRow{}
	for rows.Next() {
		var i ListProductsByOrganizationWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.IsFeatured,
			&i.Specification,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE
    products
SET
    category_id = $3,
    name = $4,
    slug = $5,
    description = $6,
    specification = $7,
    "status" = $8,
    is_featured = $9,
    updated_at = NOW()
WHERE
    id = $1
    AND organization_id = $2
RETURNING
    id, organization_id, category_id, name, slug, description, status, specification, is_featured, idempotency_key, created_at, updated_at
`

type UpdateProductParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Specification  []byte    `json:"specification"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.OrganizationID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Specification,
		arg.Status,
		arg.IsFeatured,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Specification,
		&i.IsFeatured,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStatus = `-- name: UpdateProductStatus :one
UPDATE
    products
SET
    "status" = $3,
    updated_at = NOW()
WHERE
    id = $1
    AND organization_id = $2
RETURNING
    id,
    "status",
    updated_at
`

type UpdateProductStatusParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         string    `json:"status"`
}

type UpdateProductStatusRow struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (UpdateProductStatusRow, error) {
	row := q.db.QueryRow(ctx, updateProductStatus, arg.ID, arg.OrganizationID, arg.Status)
	var i UpdateProductStatusRow
	err := row.Scan(&i.ID, &i.Status, &i.UpdatedAt)
	return i, err
}
