// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    organization_id
    , category_id
    , name
    , slug
    , description
    , specification
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, category_id, name, slug, description, status, specification, is_featured, created_at, updated_at
`

type CreateProductParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Specification  []byte    `json:"specification"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrganizationID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Specification,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.Specification,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id
    , organization_id
    , category_id
    , name
    , slug
    , description
    , status
    , is_featured
    , specification
    , created_at
    , updated_at
FROM products
WHERE id = $1
ORDER BY id
LIMIT 1
`

type GetProductByIDRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CategoryID     uuid.UUID `json:"category_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    []byte    `json:"description"`
	Status         string    `json:"status"`
	IsFeatured     bool      `json:"is_featured"`
	Specification  []byte    `json:"specification"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.IsFeatured,
		&i.Specification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
