// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignAttributeValueToProductVariant(ctx context.Context, arg AssignAttributeValueToProductVariantParams) error
	AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error
	CountPlatformAdmins(ctx context.Context) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error)
	CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateCustomerAccount(ctx context.Context, arg CreateCustomerAccountParams) (CreateCustomerAccountRow, error)
	CreateIdentity(ctx context.Context, type_ string) (Identity, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductAsset(ctx context.Context, arg CreateProductAssetParams) (ProductAsset, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (CreateUserAccountRow, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error)
	DeleteAllOtherSessionsByIdentity(ctx context.Context, arg DeleteAllOtherSessionsByIdentityParams) error
	DeleteAllSessionsByIdentity(ctx context.Context, identityID uuid.UUID) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteProductAssetsByProductID(ctx context.Context, productID uuid.UUID) error
	DeleteProductVariant(ctx context.Context, arg DeleteProductVariantParams) error
	DeleteSessionByIDAndIdentity(ctx context.Context, arg DeleteSessionByIDAndIdentityParams) (uuid.UUID, error)
	DeleteSessionByToken(ctx context.Context, token string) error
	DeleteVariantAttributes(ctx context.Context, productVariantID uuid.UUID) error
	GetActiveProductByID(ctx context.Context, id uuid.UUID) (GetActiveProductByIDRow, error)
	GetActiveProductBySlug(ctx context.Context, arg GetActiveProductBySlugParams) (GetActiveProductBySlugRow, error)
	GetAddressByID(ctx context.Context, id uuid.UUID) (GetAddressByIDRow, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCustomerAccountByID(ctx context.Context, customerID uuid.UUID) (GetCustomerAccountByIDRow, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByIdentityID(ctx context.Context, identityID uuid.UUID) (Customer, error)
	GetCustomerHashedPassword(ctx context.Context, arg GetCustomerHashedPasswordParams) (*string, error)
	GetCustomerWithCredential(ctx context.Context, email string) (GetCustomerWithCredentialRow, error)
	GetIdentity(ctx context.Context, id uuid.UUID) (Identity, error)
	GetInventoryByVariantAndWarehouseForOrganization(ctx context.Context, arg GetInventoryByVariantAndWarehouseForOrganizationParams) (GetInventoryByVariantAndWarehouseForOrganizationRow, error)
	GetMemberByIdentityID(ctx context.Context, identityID uuid.UUID) (Member, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductByIdempotencyKey(ctx context.Context, arg GetProductByIdempotencyKeyParams) (Product, error)
	GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (GetProductBySlugRow, error)
	GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error)
	GetRoleByID(ctx context.Context, id int16) (Role, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetSessionWithIdentity(ctx context.Context, token string) (GetSessionWithIdentityRow, error)
	GetUserAccountByID(ctx context.Context, userID uuid.UUID) (GetUserAccountByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByIdentityID(ctx context.Context, identityID uuid.UUID) (User, error)
	GetUserHashedPassword(ctx context.Context, arg GetUserHashedPasswordParams) (*string, error)
	GetUserWithCredential(ctx context.Context, email string) (GetUserWithCredentialRow, error)
	GetWarehouseByIDAndOrganization(ctx context.Context, arg GetWarehouseByIDAndOrganizationParams) (GetWarehouseByIDAndOrganizationRow, error)
	GetWarehouseVariantInventory(ctx context.Context, arg GetWarehouseVariantInventoryParams) (Inventory, error)
	ListActiveProductsAfter(ctx context.Context, arg ListActiveProductsAfterParams) ([]ListActiveProductsAfterRow, error)
	ListInventoryByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListInventoryByOrganizationRow, error)
	ListInventoryByProduct(ctx context.Context, arg ListInventoryByProductParams) ([]ListInventoryByProductRow, error)
	ListInventoryByVariant(ctx context.Context, arg ListInventoryByVariantParams) ([]ListInventoryByVariantRow, error)
	ListOrganizationRolesByType(ctx context.Context, arg ListOrganizationRolesByTypeParams) ([]Role, error)
	ListProductAssetsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductAsset, error)
	ListProductAssetsByProductIDs(ctx context.Context, productIds []uuid.UUID) ([]ProductAsset, error)
	ListProductVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error)
	ListProductVariantsByProductIDs(ctx context.Context, productIds []uuid.UUID) ([]ProductVariant, error)
	ListProductsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListProductsByOrganizationRow, error)
	ListProductsByOrganizationWithStatus(ctx context.Context, arg ListProductsByOrganizationWithStatusParams) ([]ListProductsByOrganizationWithStatusRow, error)
	ListSessionsByIdentity(ctx context.Context, arg ListSessionsByIdentityParams) ([]ListSessionsByIdentityRow, error)
	ListVariantAttributesByProduct(ctx context.Context, productID uuid.UUID) ([]ListVariantAttributesByProductRow, error)
	ListVariantAttributesByProductIDs(ctx context.Context, productIds []uuid.UUID) ([]ListVariantAttributesByProductIDsRow, error)
	ListWarehousesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListWarehousesByOrganizationRow, error)
	RenewSession(ctx context.Context, arg RenewSessionParams) error
	UpdateAddressByIDAndOrganization(ctx context.Context, arg UpdateAddressByIDAndOrganizationParams) (Address, error)
	UpdateCustomerAccount(ctx context.Context, arg UpdateCustomerAccountParams) (UpdateCustomerAccountRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (UpdateProductStatusRow, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateUserAccount(ctx context.Context, arg UpdateUserAccountParams) (UpdateUserAccountRow, error)
	UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (Warehouse, error)
	// If either ID does not belong to the organization, the SELECT below returns no
	// rows. sqlc maps that empty RETURNING result to ErrNotFound for the handler.
	UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (Inventory, error)
}

var _ Querier = (*Queries)(nil)
