// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignAttributeValueToProductVariant(ctx context.Context, arg AssignAttributeValueToProductVariantParams) error
	AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error)
	CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateCustomerAccount(ctx context.Context, arg CreateCustomerAccountParams) (CreateCustomerAccountRow, error)
	CreateIdentity(ctx context.Context, type_ string) (Identity, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductAsset(ctx context.Context, arg CreateProductAssetParams) (ProductAsset, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (CreateUserAccountRow, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error)
	GetAddressByID(ctx context.Context, id uuid.UUID) (GetAddressByIDRow, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCustomerAccountByID(ctx context.Context, customerID uuid.UUID) (GetCustomerAccountByIDRow, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerHashedPassword(ctx context.Context, arg GetCustomerHashedPasswordParams) (*string, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error)
	GetRoleByID(ctx context.Context, id int16) (Role, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetUserAccountByID(ctx context.Context, userID uuid.UUID) (GetUserAccountByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserHashedPassword(ctx context.Context, arg GetUserHashedPasswordParams) (*string, error)
	GetWarehouseVariantInventory(ctx context.Context, arg GetWarehouseVariantInventoryParams) (Inventory, error)
	ListOrganizationRolesByType(ctx context.Context, arg ListOrganizationRolesByTypeParams) ([]Role, error)
	UpdateCustomerAccount(ctx context.Context, arg UpdateCustomerAccountParams) (UpdateCustomerAccountRow, error)
	UpdateUserAccount(ctx context.Context, arg UpdateUserAccountParams) (UpdateUserAccountRow, error)
}

var _ Querier = (*Queries)(nil)
