// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    role_name
    , organization_id
    , organization_type
    , slug
    , is_system
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, role_name, organization_id, organization_type, slug, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	RoleName         string     `json:"role_name"`
	OrganizationID   *uuid.UUID `json:"organization_id"`
	OrganizationType string     `json:"organization_type"`
	Slug             string     `json:"slug"`
	IsSystem         bool       `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.RoleName,
		arg.OrganizationID,
		arg.OrganizationType,
		arg.Slug,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.OrganizationID,
		&i.OrganizationType,
		&i.Slug,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT
    id
    , role_name
    , organization_id
    , organization_type
    , slug
    , is_system
    , created_at
    , updated_at
FROM roles
WHERE id = $1
ORDER BY id
LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int16) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.OrganizationID,
		&i.OrganizationType,
		&i.Slug,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT
    id
    , role_name
    , organization_id
    , organization_type
    , slug
    , is_system
    , created_at
    , updated_at
FROM roles
WHERE slug = $1
ORDER BY id
LIMIT 1
`

func (q *Queries) GetRoleBySlug(ctx context.Context, slug string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.OrganizationID,
		&i.OrganizationType,
		&i.Slug,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationRolesByType = `-- name: ListOrganizationRolesByType :many
SELECT
    id
    , role_name
    , organization_id
    , organization_type
    , slug
    , is_system
    , created_at
    , updated_at
FROM roles
WHERE
    organization_id IS null
    OR organization_id = $1
    AND organization_type = $2
ORDER BY id
`

type ListOrganizationRolesByTypeParams struct {
	OrganizationID   *uuid.UUID `json:"organization_id"`
	OrganizationType string     `json:"organization_type"`
}

func (q *Queries) ListOrganizationRolesByType(ctx context.Context, arg ListOrganizationRolesByTypeParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listOrganizationRolesByType, arg.OrganizationID, arg.OrganizationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.OrganizationID,
			&i.OrganizationType,
			&i.Slug,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
