// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO
    sessions (
        identity_id,
        token,
        service,
        expires_at,
        ip_address,
        user_agent,
        active_organization_id
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, identity_id, active_organization_id, token, service, expires_at, ip_address, user_agent, created_at, updated_at
`

type CreateSessionParams struct {
	IdentityID           uuid.UUID  `json:"identity_id"`
	Token                string     `json:"token"`
	Service              string     `json:"service"`
	ExpiresAt            time.Time  `json:"expires_at"`
	IpAddress            *string    `json:"ip_address"`
	UserAgent            *string    `json:"user_agent"`
	ActiveOrganizationID *uuid.UUID `json:"active_organization_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.IdentityID,
		arg.Token,
		arg.Service,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.ActiveOrganizationID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.ActiveOrganizationID,
		&i.Token,
		&i.Service,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllOtherSessionsByIdentity = `-- name: DeleteAllOtherSessionsByIdentity :exec
DELETE FROM
    sessions
WHERE
    identity_id = $1
    AND service = $2
    AND token <> $3
`

type DeleteAllOtherSessionsByIdentityParams struct {
	IdentityID uuid.UUID `json:"identity_id"`
	Service    string    `json:"service"`
	Token      string    `json:"token"`
}

func (q *Queries) DeleteAllOtherSessionsByIdentity(ctx context.Context, arg DeleteAllOtherSessionsByIdentityParams) error {
	_, err := q.db.Exec(ctx, deleteAllOtherSessionsByIdentity, arg.IdentityID, arg.Service, arg.Token)
	return err
}

const deleteAllSessionsByIdentity = `-- name: DeleteAllSessionsByIdentity :exec
DELETE FROM
    sessions
WHERE
    identity_id = $1
`

func (q *Queries) DeleteAllSessionsByIdentity(ctx context.Context, identityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsByIdentity, identityID)
	return err
}

const deleteSessionByIDAndIdentity = `-- name: DeleteSessionByIDAndIdentity :one
DELETE FROM
    sessions
WHERE
    id = $1
    AND identity_id = $2
RETURNING
    id
`

type DeleteSessionByIDAndIdentityParams struct {
	ID         uuid.UUID `json:"id"`
	IdentityID uuid.UUID `json:"identity_id"`
}

func (q *Queries) DeleteSessionByIDAndIdentity(ctx context.Context, arg DeleteSessionByIDAndIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteSessionByIDAndIdentity, arg.ID, arg.IdentityID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM
    sessions
WHERE
    token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}

const getSessionWithIdentity = `-- name: GetSessionWithIdentity :one
SELECT
    s.id AS session_id,
    s.identity_id,
    s.token,
    s.service,
    s.expires_at,
    s.ip_address,
    s.user_agent,
    s.created_at,
    s.updated_at,
    s.active_organization_id,
    i.type AS identity_type
FROM
    sessions s
    JOIN identities i ON s.identity_id = i.id
WHERE
    s.token = $1
    AND s.expires_at > NOW()
LIMIT
    1
`

type GetSessionWithIdentityRow struct {
	SessionID            uuid.UUID  `json:"session_id"`
	IdentityID           uuid.UUID  `json:"identity_id"`
	Token                string     `json:"token"`
	Service              string     `json:"service"`
	ExpiresAt            time.Time  `json:"expires_at"`
	IpAddress            *string    `json:"ip_address"`
	UserAgent            *string    `json:"user_agent"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	ActiveOrganizationID *uuid.UUID `json:"active_organization_id"`
	IdentityType         string     `json:"identity_type"`
}

func (q *Queries) GetSessionWithIdentity(ctx context.Context, token string) (GetSessionWithIdentityRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithIdentity, token)
	var i GetSessionWithIdentityRow
	err := row.Scan(
		&i.SessionID,
		&i.IdentityID,
		&i.Token,
		&i.Service,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveOrganizationID,
		&i.IdentityType,
	)
	return i, err
}

const listSessionsByIdentity = `-- name: ListSessionsByIdentity :many
SELECT
    id,
    service,
    ip_address,
    user_agent,
    created_at,
    updated_at,
    expires_at
FROM
    sessions
WHERE
    identity_id = $1
    AND service = $2
    AND expires_at > NOW()
ORDER BY
    updated_at DESC
`

type ListSessionsByIdentityParams struct {
	IdentityID uuid.UUID `json:"identity_id"`
	Service    string    `json:"service"`
}

type ListSessionsByIdentityRow struct {
	ID        uuid.UUID `json:"id"`
	Service   string    `json:"service"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ListSessionsByIdentity(ctx context.Context, arg ListSessionsByIdentityParams) ([]ListSessionsByIdentityRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByIdentity, arg.IdentityID, arg.Service)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByIdentityRow{}
	for rows.Next() {
		var i ListSessionsByIdentityRow
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSession = `-- name: RenewSession :exec
UPDATE
    sessions
SET
    expires_at = $1::TIMESTAMPTZ
WHERE
    token = $2
    AND expires_at > NOW()
`

type RenewSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	Token     string    `json:"token"`
}

func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) error {
	_, err := q.db.Exec(ctx, renewSession, arg.ExpiresAt, arg.Token)
	return err
}
