// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (identity_id, name, email)
VALUES
    ($1, $2, $3)
RETURNING
    id, identity_id, name, email, email_verified, image, created_at, updated_at
`

type CreateUserParams struct {
	IdentityID uuid.UUID `json:"identity_id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.IdentityID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    identity_id,
    name,
    email,
    email_verified,
    image,
    created_at,
    updated_at
FROM
    users
WHERE
    email = $1
ORDER BY
    id
LIMIT
    1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentityID = `-- name: GetUserByIdentityID :one
SELECT
    id,
    identity_id,
    name,
    email,
    email_verified,
    image,
    created_at,
    updated_at
FROM
    users
WHERE
    identity_id = $1
LIMIT
    1
`

func (q *Queries) GetUserByIdentityID(ctx context.Context, identityID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentityID, identityID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithCredential = `-- name: GetUserWithCredential :one
SELECT
    u.id,
    u.identity_id,
    u.name,
    u.email,
    ua.hashed_password
FROM
    users u
LEFT JOIN user_accounts ua
    ON u.id = ua.user_id AND ua.provider_id = 'credential'
WHERE
    u.email = $1
LIMIT 1
`

type GetUserWithCredentialRow struct {
	ID             uuid.UUID `json:"id"`
	IdentityID     uuid.UUID `json:"identity_id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword *string   `json:"hashed_password"`
}

func (q *Queries) GetUserWithCredential(ctx context.Context, email string) (GetUserWithCredentialRow, error) {
	row := q.db.QueryRow(ctx, getUserWithCredential, email)
	var i GetUserWithCredentialRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
