// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_account.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (
    user_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , hashed_password
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id
    , user_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , created_at
    , updated_at
`

type CreateUserAccountParams struct {
	UserID                uuid.UUID  `json:"user_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	HashedPassword        *string    `json:"hashed_password"`
}

type CreateUserAccountRow struct {
	ID                    uuid.UUID  `json:"id"`
	UserID                uuid.UUID  `json:"user_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (CreateUserAccountRow, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.UserID,
		arg.AccountID,
		arg.ProviderID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.Scope,
		arg.IDToken,
		arg.HashedPassword,
	)
	var i CreateUserAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByID = `-- name: GetUserAccountByID :one
SELECT
    id
    , user_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , created_at
    , updated_at
FROM user_accounts
WHERE user_id = $1
ORDER BY id
LIMIT 1
`

type GetUserAccountByIDRow struct {
	ID                    uuid.UUID  `json:"id"`
	UserID                uuid.UUID  `json:"user_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserAccountByID(ctx context.Context, userID uuid.UUID) (GetUserAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAccountByID, userID)
	var i GetUserAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserHashedPassword = `-- name: GetUserHashedPassword :one
SELECT hashed_password
FROM user_accounts
WHERE user_id = $1 AND provider_id = $2
ORDER BY id
LIMIT 1
`

type GetUserHashedPasswordParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ProviderID string    `json:"provider_id"`
}

func (q *Queries) GetUserHashedPassword(ctx context.Context, arg GetUserHashedPasswordParams) (*string, error) {
	row := q.db.QueryRow(ctx, getUserHashedPassword, arg.UserID, arg.ProviderID)
	var hashed_password *string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const updateUserAccount = `-- name: UpdateUserAccount :one
UPDATE user_accounts
SET
    access_token = coalesce($2, access_token)
    , refresh_token = coalesce($3, refresh_token)
    , access_token_expires_at = coalesce($4, access_token_expires_at)
    , refresh_token_expires_at = coalesce($5, refresh_token_expires_at)
    , id_token = coalesce($6, id_token)
    , scope = coalesce($7, scope)
    , hashed_password = coalesce($8, hashed_password)
WHERE id = $1
RETURNING
    id
    , user_id
    , account_id
    , provider_id
    , access_token
    , refresh_token
    , access_token_expires_at
    , refresh_token_expires_at
    , scope
    , id_token
    , created_at
    , updated_at
`

type UpdateUserAccountParams struct {
	ID                    uuid.UUID  `json:"id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	IDToken               *string    `json:"id_token"`
	Scope                 *string    `json:"scope"`
	HashedPassword        *string    `json:"hashed_password"`
}

type UpdateUserAccountRow struct {
	ID                    uuid.UUID  `json:"id"`
	UserID                uuid.UUID  `json:"user_id"`
	AccountID             string     `json:"account_id"`
	ProviderID            string     `json:"provider_id"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	IDToken               *string    `json:"id_token"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserAccount(ctx context.Context, arg UpdateUserAccountParams) (UpdateUserAccountRow, error) {
	row := q.db.QueryRow(ctx, updateUserAccount,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.IDToken,
		arg.Scope,
		arg.HashedPassword,
	)
	var i UpdateUserAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IDToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
