// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouse.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (
    organization_id
    , name
    , address_id
) VALUES ($1, $2, $3)
RETURNING id, organization_id, name, address_id, is_active
`

type CreateWarehouseParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	AddressID      uuid.UUID `json:"address_id"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse, arg.OrganizationID, arg.Name, arg.AddressID)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AddressID,
		&i.IsActive,
	)
	return i, err
}
